### PR TITLE
Making `json_encode()` always produce a `non-empty-string`, when successful

### PR DESCRIPTION
**Pull request by Ocramius**
`json_encode()` never produces `''` as a value: that would be invalid JSON anyway

### CODE REVIEW

**Comment by danog** [comment]
Would you please target this against master, we'll be releasing 5 in the coming days anyway :)

**Comment by Ocramius** [comment]
Sure thing: I targeted 4.x because I thought it would still apply 😁

**Comment by Ocramius** [comment]
@danog done

**Comment by orklah** [comment]
I don't get how the CI go bonkers everytime there's a switch like that... Sorry Marco, could you do a rebase on master to relaunch the CI please?

**Comment by Ocramius** [comment]
It's already rebased :| 

Lemme add some gibberish to the patch, like whitespace to the commit.

**Comment by orklah** [comment]
Seems working :) Thanks!

**Comment by orklah** [comment]
Thanks!

**Comment by Ocramius** [comment]
Thank **you** for merging so quickly! :)

**Pull request merged**
