### PR TITLE
Fix/phpparser deprecation name parts

### PR DESCRIPTION
**Pull request by ygottschalk**

### CODE REVIEW

**Comment by orklah** [comment]
Looks great!

You may want to add a stub for toString to document that it returns a non-empty-string here: 
https://github.com/vimeo/psalm/blob/master/stubs/phpparser.phpstub#L8

Or even propose documenting it upstream for a future version :)

**Comment by ygottschalk** [comment]
Don't have time to finish this rn. Feel free to continue where I left. 

cc @orklah

**Comment by ygottschalk** [comment]
Analysis of constructor on stubbed classes seems to be unsupported. Did not manage to get it working so I choose to just supress the issue.
IMO ready to merge @orklah

**Comment by orklah** [comment]
There are two weird issue on Shepherd left but I guess we can fix that later

Thanks a lot for this, it's great :)

**Comment by bemulima** [comment]
Sorry for first. But I don't know is this my question also. When I tried:
```
./vendor/bin/psalm --init
```

I got mistake:

```
./vendor/bin/psalm --init
Calculating best config level based on project files
Calculating best config level based on project files
Target PHP version: 8.0 (inferred from composer.json) Enabled extensions: simplexml (unsupported extensions: fileinfo).
Scanning files...
Uncaught Error: Call to undefined method PhpParser\Node\Name::getParts() in /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php:373
Stack trace:
#0 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(287): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#1 /var/www/job/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#2 /var/www/job/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#3 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(79): PhpParser\NodeTraverser->traverse()
#4 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(558): Psalm\Internal\Scanner\FileScanner->scan()
#5 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(785): Psalm\Internal\Codebase\Scanner->scanFile()
#6 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(428): Psalm\Internal\Codebase\Scanner->scanAPath()
#7 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#8 /var/www/job/vendor/vimeo/psalm/src/Psalm/Config.php(2493): Psalm\Internal\Codebase\Scanner->scanFiles()
#9 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(372): Psalm\Config->visitComposerAutoloadFiles()
#10 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(502): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#11 /var/www/job/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#12 /var/www/job/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#13 /var/www/job/vendor/bin/psalm(119): include('...')
#14 {main}
(Psalm 5.x-dev@07acefd0b6ec7e5f73af66b9479ae39e943a2214 crashed due to an uncaught Throwable)

```

So how to init if there has conflict with phpParser? I just want work easier with psalm in nvim (lsp)

**Comment by bemulima** [comment]
my psalm version is:
```
./vendor/bin/psalm --version
Psalm 5.x-dev@07acefd0b6ec7e5f73af66b9479ae39e943a2214

```

in case psam/composer.json:

```
{
    "name": "vimeo/psalm",
    "type": "project",
    "description": "A static analysis tool for finding errors in PHP applications",
    "keywords": [
        "php",
        "code",
        "inspection",
        "static analysis"
    ],
    "license": "MIT",
    "authors": [
        {
            "name": "Matthew Brown"
        }
    ],
    "require": {
        "php": "^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0",
        "ext-SimpleXML": "*",
        "ext-ctype": "*",
        "ext-dom": "*",
        "ext-json": "*",
        "ext-libxml": "*",
        "ext-mbstring": "*",
        "ext-tokenizer": "*",
        "composer-runtime-api": "^2",
        "amphp/amp": "^2.4.2",
        "amphp/byte-stream": "^1.5",
        "composer/semver": "^1.4 || ^2.0 || ^3.0",
        "composer/xdebug-handler": "^2.0 || ^3.0",
        "dnoegel/php-xdg-base-dir": "^0.1.1",
        "felixfbecker/advanced-json-rpc": "^3.1",
        "felixfbecker/language-server-protocol": "^1.5.2",
        "fidry/cpu-core-counter": "^0.4.1 || ^0.5.1",
        "netresearch/jsonmapper": "^1.0 || ^2.0 || ^3.0 || ^4.0",
        "nikic/php-parser": "^4.16",
        "sebastian/diff": "^4.0 || ^5.0",
        "spatie/array-to-xml": "^2.17.0 || ^3.0",
        "symfony/console": "^4.1.6 || ^5.0 || ^6.0 || ^7.0",
        "symfony/filesystem": "^5.4 || ^6.0 || ^7.0"
    },
    "conflict": {
      "nikic/php-parser": "4.17.0"
    },
    "provide": {
        "psalm/psalm": "self.version"
    },
    "require-dev": {
        "ext-curl": "*",
        "amphp/phpunit-util": "^2.0",
        "bamarni/composer-bin-plugin": "^1.4",
        "brianium/paratest": "^6.9",
        "mockery/mockery": "^1.5",
        "nunomaduro/mock-final-classes": "^1.1",
        "php-parallel-lint/php-parallel-lint": "^1.2",
        "phpstan/phpdoc-parser": "^1.6",
        "phpunit/phpunit": "^9.6",
        "psalm/plugin-mockery": "^1.1",
        "psalm/plugin-phpunit": "^0.18",
        "slevomat/coding-standard": "^8.4",
        "squizlabs/php_codesniffer": "^3.6",
        "symfony/process": "^4.4 || ^5.0 || ^6.0 || ^7.0"
    },
    "suggest": {
        "ext-igbinary": "^2.0.5 is required, used to serialize caching data",
        "ext-curl": "In order to send data to shepherd"
    },
    "config": {
        "allow-plugins": {
            "bamarni/composer-bin-plugin": true,
            "composer/package-versions-deprecated": true,
            "dealerdirect/phpcodesniffer-composer-installer": true
        },
        "optimize-autoloader": true,
        "sort-packages": true,
        "platform-check": true
    },
    "extra": {
        "branch-alias": {
            "dev-master": "5.x-dev",
            "dev-4.x": "4.x-dev",
            "dev-3.x": "3.x-dev",
            "dev-2.x": "2.x-dev",
            "dev-1.x": "1.x-dev"
        }
    },
    "autoload": {
        "psr-4": {
            "Psalm\\": "src/Psalm/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Psalm\\Tests\\": "tests/"
        }
    },
    "repositories": [
        {
            "type": "path",
            "url": "examples/plugins/composer-based/echo-checker"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "bin": [
        "psalm",
        "psalm-language-server",
        "psalm-plugin",
        "psalm-refactor",
        "psalter"
    ],
    "scripts": {
        "cs": "phpcs -ps",
        "cs-fix": "phpcbf -ps",
        "lint": "parallel-lint ./src ./tests",
        "phpunit": [
            "Composer\\Config::disableProcessTimeout",
            "paratest --runner=WrapperRunner"
        ],
        "phpunit-std": [
            "Composer\\Config::disableProcessTimeout",
            "phpunit"
        ],
        "verify-callmap": "@php phpunit tests/Internal/Codebase/InternalCallMapHandlerTest.php",
        "psalm": "@php ./psalm",
        "psalm-set-baseline": "@php ./psalm --set-baseline=psalm-baseline.xml",
        "tests": [
            "@lint",
            "@cs",
            "@psalm",
            "@phpunit"
        ]
    },
    "scripts-descriptions": {
        "cs": "Checks that the code conforms to the coding standard.",
        "cs-fix": "Automatically correct coding standard violations.",
        "lint": "Lint php files.",
        "phpunit": "Runs unit tests in parallel.",
        "phpunit-std": "Runs unit tests.",
        "psalm": "Runs static analysis.",
        "tests": "Runs all available tests."
    },
    "support": {
      "docs": "https://psalm.dev/docs",
      "issues": "https://github.com/vimeo/psalm/issues",
      "source": "https://github.com/vimeo/psalm"
    }
}
```



in case php-parser/composer.json:

```
{
    "name": "nikic/php-parser",
    "type": "library",
    "description": "A PHP parser written in PHP",
    "keywords": [
        "php",
        "parser"
    ],
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Nikita Popov"
        }
    ],
    "require": {
        "php": ">=7.0",
        "ext-tokenizer": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^6.5 || ^7.0 || ^8.0 || ^9.0",
        "ircmaxell/php-yacc": "^0.0.7"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "4.9-dev"
        }
    },
    "autoload": {
        "psr-4": {
            "PhpParser\\": "lib/PhpParser"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "PhpParser\\": "test/PhpParser/"
        }
    },
    "bin": [
        "bin/php-parse"
    ]
}
```

**Pull request merged**
