### PR TITLE
Make --init use vendor-dir from composer.json

### LINKED ISSUE #2137: query re: getVendorDir()
It looks like the `getVendorDir()` isn't used with `psalm --init`- how much of a pita would it be to add that in?

### PR DESCRIPTION
**Pull request by jorams**
Fixes #2137

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by SignpostMarv** [comment]
:D

**Comment by joendres** [comment]
> Fixes #2137

I'm afraid it doesn't fully: There are two more hard coded 'vendor' strings in
Config.php, visitComposerAutoloadFiles(...) and
Config\Creator.php, guessPhpFileDirs(…).

**Comment by SignpostMarv** [comment]
@joendres Is the specific example identified in [example repo](https://github.com/SignpostMarv/psalm-issue-2137/blob/b04eaf74574bfb84748def7ea04970fc7d8303f5/psalm.xml#L12) resolved?

**Comment by joendres** [comment]
Sorry, my fault, you are Right: #2137 only covers the --init issue and this pull request fixes that.

I'll build an example that shows the effect of the remaining bugs and then open a new issue for that.

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
