### PR TITLE
Disallow `never` type for parameters

### PR DESCRIPTION
**Pull request by tuqqu**

### CODE REVIEW

**Comment by orklah** [comment]
What's the purpose of this check? There's probably some fringe cases where having a never param could be useful and I don't think it would find a lot of bugs in projects

**Comment by tuqqu** [comment]
@orklah it's a fatal error in PHP, https://3v4l.org/TSL24

**Comment by orklah** [comment]
Oh, I didn't know, that's great then!

**Comment by bdsl** [comment]
Since a value of never can never exist, a function that takes a never argument can never be called and is therefore technically useless.

There was an RFC to allow never in params but those functions would still have been unusable - the point was to have subclasses extend them into usable functions by replacing never with some other type, as a way to work around the lack of generics. The RFC was not accepted.

**Pull request merged**
