### PR TITLE
Partial attempt to fix global type taint issue 8359

### PR DESCRIPTION
**Pull request by mmcev106**
This PR to fix issue #8359 is still in the works!

### CODE REVIEW

**Comment by mmcev106** [comment]
@orklah, I believe this PR implements your recommendations from [here](https://github.com/vimeo/psalm/issues/8359#issuecomment-1203132090).  I've verified that `VariableFetchAnalyzer::taintVariable()` is getting called with a `$type` argument of `mysqli`, but the unit test is still failing to detect the taint.  Do you have any other recommendations?

**Comment by orklah** [comment]
I don't have any more idea as to why the taint is not detected here. About failing tests, I suppose this broke this condition:
https://github.com/vimeo/psalm/blob/58e87fa5e0cb8c76d8dd8ae4423342a47b35d403/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php#L910
It was using isSuperGlobal as well and it seems to be the one that breaks.

**Comment by weirdan** [comment]
4.x branch is closed now as we prepare for the 5.0 release. Please target the master branch instead.

**Comment by mmcev106** [comment]
@weirdan, I'm happy to rewrite the PR for the master branch.  However, I haven't yet figured out what to do differently yet to make the PR work as @orklah originally envisioned.

To follow up on the test failure comments, I think @orklah & I were talking about different tests.  I have yet to make the test case I added for this PR pass (regardless of other tests/cases)

**Comment by orklah** [comment]
Sorry for not getting back to you before. I'm not sure why everything broke, it would have to be debugged step by step to find out. It's even possible my solution can't work for some reason.

I'll close this for now given it targets a closed branch. The issues will be kept open for tracking the issue though

**Comment by mmcev106** [comment]
@orklah, thanks very much for the input.  There's a chance I will have a bigger block of time to dig into https://github.com/vimeo/psalm/issues/8359 in the next few months.

**Pull request closed without merging**
