### PR TITLE
Fix typos noticed in docs

### PR DESCRIPTION
**Pull request by TysonAndre**

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by muglug** [comment]
Do you understand why I created Psalm now? Also, emailed you two days ago (but from a different, non-github address) - not sure you received

**Comment by TysonAndre** [comment]
> Do you understand why I created Psalm now? 

Yes - because it's useful. I'm not sure why you ask?

>  Also, emailed you two days ago 

I received that message. Thanks - I didn't know if you were expecting a response.

**Comment by muglug** [comment]
> > Do you understand why I created Psalm now?

> Yes - because it's useful. I'm not sure why you ask?

It was a joke - because of the occasional random mistakes in my work, a few of which were fixed in this PR

> I didn't know if you were expecting a response.

Oh I wasn't really, just thought there was a chance it might have gone to junk bc it was from a different address. Anyway, carry on.

**Pull request merged**
