### PR TITLE
Fixed callmap for function openssl_sign, it changed in PHP 8.0 (modif…

### PR DESCRIPTION
**Pull request by jirkace**
…ied types for param private_key)  #6842

### CODE REVIEW

**Comment by weirdan** [comment]
The docs say `array` is also accepted as a private key. For the array format, see https://www.php.net/manual/en/openssl.certparams.php:

```
For private keys, you may also use the syntax `array($key, $passphrase)` where `$key` represents a key specified using the `file://` or textual content notation above, and `$passphrase` represents a string containing the passphrase for that private key 
```

**Comment by jirkace** [comment]
@weirdan I'm sorry about that and thanks for notice. Is `list<string>` correct type notation for that `array` in CallMap? I've updated it PR.

**Comment by weirdan** [comment]
I'm not sure, it may accept `array{OpenSSLAsymmetricKey|OpenSSLCertificate|string, string}`, and I don't have `openssl` extension installed to test it.

Anyway, `list` would be better replaced with a tuple like shown above, as docs clearly suggest the function expects two-element array, and `list` allows any number of elements (including 0).

**Comment by jirkace** [comment]
@weirdan I've tried locally run snippet of code and it looks like it works with `array{OpenSSLAsymmetricKey, string}` although I understand from the documentation that it can only be there `array{string, string}`

> $key represents a key specified using the file:// or textual content notation

`textual content notation` is `string` only for me :-)

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
