### PR TITLE
Template and variable types inference for methods marked with psalm-if-this-is

### LINKED ISSUE #7258: `psalm-if-this-is` enhancements
This example raises many issues: https://psalm.dev/r/8f7f7985a6

All issues can be fixed if:
1) `$this` variables will be inferred from `psalm-if-this-is`
2) template params will be resolved from `psalm-if-this-is`

### PR DESCRIPTION
**Pull request by klimick**
Closes #7258

### CODE REVIEW

**Comment by klimick** [comment]
I see many psalm issues that unrelated to the new code. Master branch was corrupted?

**Comment by klimick** [comment]
Don't know what to do with Psalm errors and where they came from)

**Comment by orklah** [comment]
Test still pass on master after a re-run: https://github.com/vimeo/psalm/actions/runs/1642095334

It must be caused by something in your PR

**Comment by orklah** [comment]
Give me a sign if you're stuck, I'll try to clone your PR and check it out

**Comment by klimick** [comment]
Solved. In some situations MethodStorage was null.

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
