### PR TITLE
[wip] replace composer/composer with composer/xdebug-handler

### PR DESCRIPTION
**Pull request by weirdan**
Fixes vimeo/psalm#349

Note: there's no stable release at the moment, so it's using dev-master for now. For this reason you may want to not merge it right away and wait for stable release.

### CODE REVIEW

**Comment by muglug** [comment]
LET'S DO THIS

**Comment by muglug** [comment]
Thanks!

**Comment by muglug** [comment]
This shaves 30MB off the memory used by Psalm

**Comment by weirdan** [comment]
Beat me to it =)

**Comment by TysonAndre** [comment]
Note: xdebug-handler doesn't work properly for me when a phar file is invoked with a relative path (e.g. `php relative/path/to/phan.phar`). I already filed an issue for this.

An example workaround [used in a different project is linked here](https://github.com/phan/phan/commit/9ab746bae733e8a3f85ff3b612ff929c4a70e60b)

Aside: I noticed Psalm 1.0.5 doesn't have a phar file with the release yet (Doesn't affect me): https://github.com/vimeo/psalm/releases/tag/1.0.5

**Comment by weirdan** [comment]
@TysonAndre psalm doesn't seem to suffer from this problem, I've just checked that.

**Comment by weirdan** [comment]
And for phar missing for the latest release, it appears phar build is broken again (it reports lots of false-positives, unlike no-phar version).

**Pull request merged**
