### PR TITLE
Add option to show link to source in console output

### PR DESCRIPTION
**Pull request by the-toster**
It adds `--php-storm` option to `psalm` command, which make console output fit to phpStorm pattern of source links (`\n at {file}:{line}:{col}\n`)

I see two problems in this PR: 1) option name is not very good, and 2) this pattern is not documented (but stacktrace printed like this).

For me this option is very handy (also, it was requested here #3271 ), I'll be glad of any suggestions, how this can be done.

### CODE REVIEW

**Comment by andyg0808** [comment]
I don't really know anything about implementation details, but there are a bunch of existing report formats that are switchable via the `--output-format` option:
```sh
    --output-format=console
        Changes the output format.
        Available formats: compact, console, emacs, json, pylint, xml, checkstyle, junit, sonarqube, github
```
I would suspect that it might make sense to make this available via that list as well.
It looks to me like the implementations may be in https://github.com/vimeo/psalm/tree/master/src/Psalm/Report.

**Comment by the-toster** [comment]
I have renamed flag to `--php-storm-format`

**Comment by the-toster** [comment]
@andyg0808 At first I did as you say, but looking in current codebase I have found four `if` statements, that check type of report, this:
https://github.com/vimeo/psalm/blob/64f08fa9dca23e81862e6f2f5b73ea391ecd10e5/src/Psalm/IssueBuffer.php#L456-L461
(and they should be modified to support one more console-like format)
So, I decide do not add extra complextity to it.

**Comment by the-toster** [comment]
If new report format is prefered way, I'm ready to implement it.

**Comment by muglug** [comment]
Yeah, I'd favour a new report output format for this, as it'll provide a little more versatility to customise things the way PHPStorm likes

**Comment by the-toster** [comment]
@muglug It's ready, please take a look.
New format name is `phpstorm`, and help message changed to this (according to code style limitation of line length):
```shell
...

    --output-format=console
        Changes the output format.
        Available formats: compact, console, text, emacs, json, pylint, xml, checkstyle, junit, sonarqube, github,
                           phpstorm

...
```

Also I used `in_array` in `if` statements:
```php
        if ($this->stdout_report_options
            && in_array(
                $this->stdout_report_options->format,
                [\Psalm\Report::TYPE_CONSOLE, \Psalm\Report::TYPE_PHP_STORM]
            )
            && $this->codebase->collect_references
        ) {
```
 I dont know is it acceptable.

**Comment by the-toster** [comment]
Maybe better to add `\Psalm\Report::isConsoleLike($format)` method, instead of this repeatable `in_array`..

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
