### PR TITLE
fix json_encode return values

### PR DESCRIPTION
**Pull request by fkooman**
`json_encode` can also return `false`

### CODE REVIEW

**Comment by fkooman** [comment]
```
$ bin/psalm

ERROR: InvalidScalarArgument - src/Psalm/Clause.php:90:20 - Argument 1 of md5 expects string, string|false provided

        return md5(json_encode($this->possibilities)) .

```

Heh ;-)

**Comment by muglug** [comment]
Could you add a check for `false` there?

Something like

```php
$possibility_string = json_encode($this->possibilities);
if (!$possibility_string) {
  throw new \LogicException('Error converting possibilities to json');
}
return md5($possibility_string);
```

**Comment by fkooman** [comment]
I'm trying to do that, but running into another issue when running Psalm itself, unrelated to my changes:

```
ERROR: PropertyNotSetInConstructor - src/Psalm/Checker/ClassLikeChecker.php:140:15 - Property Psalm\Checker\TraitChecker::$storage is not defined in constructor of Psalm\Checker\TraitChecker or in any private methods called in the constructor
    protected $storage;
```

**Comment by fkooman** [comment]
It seems travis-ci is fine with running `bin/psalm` on itself. So yeah, not sure what to think of #212

**Comment by muglug** [comment]
oops sorry

**Comment by muglug** [comment]
Thanks for this!

**Pull request merged**
