### PR TITLE
Fix invalid return type in callmap.

### PR DESCRIPTION
**Pull request by ADmad**
apu_delete() only returns boolean.
http://php.net/manual/en/function.apcu-delete.php

### CODE REVIEW

**Comment by muglug** [comment]
Originally added in https://github.com/phan/phan/commit/9c51ecb199014563d11df2e8e03b42bb3dc9f905#diff-51d74031f390b02c2f3cced18a13d964 - was that a mistake @TysonAndre?

**Comment by TysonAndre** [comment]
That seems to be the case

**Comment by muglug** [comment]
No worries! Thanks @ADmad!

**Comment by ADmad** [comment]
No problem :)

**Pull request merged**
