### PR TITLE
add CodeClimate output format

### PR DESCRIPTION
**Pull request by odoucet**
This PR adds CodeClimate json format to output. 
CodeClimate is the format used by Gitlab to generate Code Quality reports.

See https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

Format spec : https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

### CODE REVIEW

**Comment by muglug** [comment]
Mind fixing the issues?

**Comment by odoucet** [comment]
PR synced with latest trunk.
Cannot access CircleCI build error :( code seems fine.

**Comment by odoucet** [comment]
updated with phpcs fixes.

**Comment by muglug** [comment]
Thanks @odoucet and @tux-rampage!

**Comment by tux-rampage** [comment]
@odoucet Thanks for this feature :+1:

**Pull request merged**
