### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by iluuu1994**

### CODE REVIEW

**Comment by iluuu1994** [comment]
[This part](https://github.com/vimeo/psalm/pull/1709/commits/3091a0eab6befa1fb297e4c0228d5f558181d84f#diff-d5bbd409b51d29291be64ae6f6df969aR254) fully solved the problem. The child now prints an error and terminates when it can't communicate with the parent.

@muglug You mind testing it out on your machine a few times?

**Comment by iluuu1994** [comment]
I honestly gotta say that I dislike the `:` character 😅

**Comment by muglug** [comment]
> @muglug You mind testing it out on your machine a few times?

yeah I'll test once I'm in the office

> I honestly gotta say that I dislike the `:` character 😅

Yeah open to changing it if people prefer `.`. The benefit of `:` is that `F` still stands out (not too much visual noise) and it's easy to tell what's Psalm's progress bar vs other tools. I guess that might be a bit of vanity, but there are often large build outputs and I don't want to add to people's mental burden when reading them.

**Comment by muglug** [comment]
Thanks so much!

**Comment by iluuu1994** [comment]
You're welcome! Let me know if I can help with anything else.

**Comment by muglug** [comment]
Output from our project (errors are suppressed via baseline)

```
FFF_FFFFFFFFFFF_FFFFFFFF__F_F_FF_F_F_F________FF____________   60 / 5576 (1%)
___F________________F_______FF______FF__________F___________  120 / 5576 (2%)
________________________________________________F___________  180 / 5576 (3%)
____________________________________________________________  240 / 5576 (4%)
________F_____________________________F_______F_F_________F_  300 / 5576 (5%)
_____________F_______F____________F___F_F____________F____F_  360 / 5576 (6%)
_F__FF____FF____F__F____F________F_____FF__FF____F_____F_F__  420 / 5576 (8%)
_____F_FF____FF___F_F_FF_F_FF_F__F_FFF__FFF___FFF_F__F_F_F__  480 / 5576 (9%)
F__FFF_F__FFFFF_FF_FFFFFFF_FF__FFFFF_FF_FF_F_F_F_FFF_FFFFFFF  540 / 5576 (10%)
_FFFFFF__FFFFFFFFF__FFFFFFF_F__F_F__FF_FFFFF_FFF_FFFFF_FFFFF  600 / 5576 (11%)
_FFF_F_FFF___FF___F_F_F_FFFF_F_F__FFFF_FFFFFF_FF__FFF____F_F  660 / 5576 (12%)
__FFFF_FFFFF_FFF__FFFF_FFFFFFFF__FFFFFF_F_F__FF__FFFFF_F_FFF  720 / 5576 (13%)
FFF_FFF_FFFFFFF_F___F_FF_FFF_FF__FF_FFFF_FFFFFF_FF_F_F__FFFF  780 / 5576 (14%)
FFFFFFFFFF__F_FFF___F_F___F__F_FFF__FFFF__F___FFFFFFF_F__FF_  840 / 5576 (15%)
_F_F_F_FFFF_FFFF___FFF_F__FFFF_FFFFF_F_F_FF_F_F_F_FF___FFFF_  900 / 5576 (16%)
F_FFF_FF_FFFFFF_FFFFFFF_FFFFFFFFFFFFFFF__FFFF_FFFFFFF_FF__F_  960 / 5576 (17%)
__FFFFFF__FFFFFF_FFFFF_FFF_FF_FF_F_FF_FFFFFFFFF_F___FFFFFFFF 1020 / 5576 (18%)
___F__F_F_FFFF_____F__F__FF__FFF_FFFF_F__FF_F__FF_F_FF_FF_F_ 1080 / 5576 (19%)
____FFF_F_F__F__FFFFFFF_F__FFF_FFFFFF_FF___F___FF____F__FF_F 1140 / 5576 (20%)
FFFFFFFFFFFF__F_FFFFF___F___FFFF_F_FFFFF__FF_F_F_FFFFFF__FFF 1200 / 5576 (22%)
F__FFFFFFFFF_FFF___F_FF_FF__F___FFF___F__F__FF___FFF__FFFFF_ 1260 / 5576 (23%)
F_FF_FFFFFFF__FF___FFFFFFFFF_FFFFF_FF_FFFF_FFFFFFFF___FFFFFF 1320 / 5576 (24%)
F__FF_FFFF____FFFF_F_FFF__F_FFFF_FFF_FFFFF__FFFF_F_F_FF_F__F 1380 / 5576 (25%)
_F__FFF__FFFFFFF____FF_F_______FFF_FF_FFFFFF__FF_FF_FFFFF_F_ 1440 / 5576 (26%)
F___F_FF_____FF__FF__F__F____FFFFFFFFF_FFFF_F_FF_FFFFFF_F_F_ 1500 / 5576 (27%)
FFFFF_F__FFF_FFF__FFFFFF__FF_FFFF_FFF_FFFFFF_FFF_F_FFFF_FFFF 1560 / 5576 (28%)
__FFFFFF_F_FFF__F_FF__FFF_FFFF_F__FFFFFF_FFFFF_FF_F_FFFFF__F 1620 / 5576 (29%)
_FF_FF__F__F__FFFFFF_FF___FF____F_FFFFFFFFF_F_F__F_FF_FF_F_F 1680 / 5576 (30%)
F_FFFFF_FF_FFFF_FF_F__F___FF_FFF__F___FFFF_F_FF_FFF_F_FFFF_F 1740 / 5576 (31%)
FFFFFF___FFFFF_FF__F_FF_FF_FFF_FF____FF_FFFF_FFF_FFFFFFF__FF 1800 / 5576 (32%)
F__F__FFFFF_FFF____FF_F_FFFF_FFF_____FF_FF_FFFFFFF_FF___FFF_ 1860 / 5576 (33%)
F_FFF_FFFF____FFF_F_____FFFFFFFFFFF_FF_FF_FFFF__FFF_FF_F_F_F 1920 / 5576 (34%)
_____FFFFFFFFF_FF_FFF__F_F__FFFFF_FFFFFFFF_FFFF__FF__FFF__F_ 1980 / 5576 (36%)
_F___FF_F__F__FF___F__F_____FF__FFFFFFF__FF__FF__F_F__FFFF_F 2040 / 5576 (37%)
FFF___F_F_F_FF_FFFFF__F_F__FFFFF_FFFF_F_F__FF_FFF_F_FFFFF_F_ 2100 / 5576 (38%)
___FFFFF__F_F_F_F____F_F__FFF_F_FF____FFF_F__F_F_F_FF__F_FFF 2160 / 5576 (39%)
_FFF__F___FFF___F_F___F_F_F___F_F__F_FF_FF_F_FF___FF___FF___ 2220 / 5576 (40%)
__FFFFFFF_F_FFFFF_F_FF_FFFF_F_F___F_F_F_____FFFFFFF_FF____F_ 2280 / 5576 (41%)
FFFFFF_FFFFFF___F__FF_FFFF___FFF____FF_FF_____F_F_F____FFF__ 2340 / 5576 (42%)
_F__F___FFF_FF_FF___F__F__FF_F_F__F____FFF_F__F___F__F__F_F_ 2400 / 5576 (43%)
FFF_F__FFF_FFF_F_FFFF_F___FFF___FFFF_F__FFFF__F_F________F__ 2460 / 5576 (44%)
___F___FF______F__FFF__F_FF______FFF_____F_FF_FFF_F__F___FF_ 2520 / 5576 (45%)
F_F__FF_FF____FF___FFF_F_F_FFF___FFFFF_FFFFFF_FF_FF_F_____FF 2580 / 5576 (46%)
___F_FFFF_F_FF__F____FFFF__FFF_F_FF___F_FF_FF__FF__F_F__F___ 2640 / 5576 (47%)
F___FF_F___F_F_F__F____F___F_FFF____F_FFF_FF_FF_F________FF_ 2700 / 5576 (48%)
FFF_F__FFFF___FFF_FF__FFFFFFFF____FF____F__FF_FF__FFF_FFFFF_ 2760 / 5576 (49%)
F_F_F_FFFFF__FFF_FF__F_F________FF_F__F_F____FF_F______FF___ 2820 / 5576 (51%)
_____FFFFFFFF__FF_FF__F_F__F_FF_F_FFF_F_F__F__FFFF__F__FFFF_ 2880 / 5576 (52%)
F__FF_____FF______F__F___F_F_________F___F_____F______F_____ 2940 / 5576 (53%)
__F__F______F_FF___F_FFFFF_F_FF___FFF_F_FFFF_______F__FFF_FF 3000 / 5576 (54%)
_______F__F_______F_F___F__FF_F___________F__F______F_____F_ 3060 / 5576 (55%)
_____F__FF___F_____F__FF_____F______________________F_____FF 3120 / 5576 (56%)
___F__F___F__F__F_______F_______F__F___________F_F____F_____ 3180 / 5576 (57%)
___F________F_____F___F_FFFFF_FF__F___F__FF__F_____F_____F__ 3240 / 5576 (58%)
____F____F_______FFF_______________F____F_F____________FF___ 3300 / 5576 (59%)
_F______F________F__F_____________F____________FF___________ 3360 / 5576 (60%)
_________F_F_F___________F________F___F________________F____ 3420 / 5576 (61%)
_____________________F__________F_____F____F__F_________F__F 3480 / 5576 (62%)
F____F____FF__F______F___F__________FF_________F____________ 3540 / 5576 (63%)
F______F_FF_FFF___F__F___F____________F__F_____F___________F 3600 / 5576 (65%)
____F_______F__FF____F_____________FFF______________________ 3660 / 5576 (66%)
_F__________F_F_________F_________F_FF___F________F____FF_FF 3720 / 5576 (67%)
_F____FFF_F__FF_F___FF______________FF_________FF___FF_FF___ 3780 / 5576 (68%)
___F_F_______F___F_____F___________F__F__F_____________F____ 3840 / 5576 (69%)
__F________________________________________F______F_________ 3900 / 5576 (70%)
_F__F_F_____F__FF__________F__________F__F_F_____F__________ 3960 / 5576 (71%)
____FFF_F_____F______F___F_FF_FF_F_F_FF____F____________F___ 4020 / 5576 (72%)
__________________F__________F__F__________F________F_______ 4080 / 5576 (73%)
___________________________________F__________F________F____ 4140 / 5576 (74%)
___________________________F___________F__F______F______F___ 4200 / 5576 (75%)
F__________F____________F___________________________________ 4260 / 5576 (76%)
___FF_________F___________________________________F______F_F 4320 / 5576 (77%)
__F_______F________________F__________F_____________________ 4380 / 5576 (79%)
__F___________________F_F_______F____FFF_______F__F____F____ 4440 / 5576 (80%)
_________F__FFFF__________F__________F________F_____________ 4500 / 5576 (81%)
________F___F_________________F_________F_F__F__________FF_F 4560 / 5576 (82%)
____FF________F_______FFF_________FF__F__FF___F_____________ 4620 / 5576 (83%)
__________FF__________F_________FFF_________________________ 4680 / 5576 (84%)
_______________F______F______F_____________F_________F______ 4740 / 5576 (85%)
_____F_______________________________________F_______F______ 4800 / 5576 (86%)
____________________F______________________________________F 4860 / 5576 (87%)
____________________________F_______________________________ 4920 / 5576 (88%)
________________________________F__________________________F 4980 / 5576 (89%)
______F_____________________________________________________ 5040 / 5576 (90%)
___F____F___________________________________________________ 5100 / 5576 (91%)
____________________F____F_____________F________F_________F_ 5160 / 5576 (93%)
___________________________________________________________F 5220 / 5576 (94%)
______________________________________F_____________________ 5280 / 5576 (95%)
______________F______________F______________________________ 5340 / 5576 (96%)
____________________F_________________F____F____F___________ 5400 / 5576 (97%)
________FF___________________________________________FF_____ 5460 / 5576 (98%)
____________________________________________F_______________ 5520 / 5576 (99%)
________________________________________________________
```

**Comment by muglug** [comment]
Maybe it's best to ignore `F` if the baseline feature is enabled

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/7c069a9ba7355e33e470907729414d1a6b847980

**Comment by muglug** [comment]
And thanks @weirdan for the assist!

**Pull request merged**
