### PR TITLE
cleanup around hrtime

### PR DESCRIPTION
**Pull request by orklah**
This PR propose cleaning up hrtime various data source to fix https://github.com/vimeo/psalm/issues/5033

- The FunctionCallReturnTypeFetcher.php file seem to return the same structure as detailed in Callmap so I removed it
- The hrtime function was introduced in PHP 7.3 so I removed it from Callmap: https://www.php.net/manual/fr/function.hrtime
- The parameter is called `as_number` internally so I updated Callmap_73

I'm not sure why there is this stack of sources where one should be enough. If CI breaks, I'll investigate more

### CODE REVIEW

**Comment by weirdan** [comment]
> so I removed it from Callmap

You shouldn't. Callmap contains the data for latest and greatest supported version, and deltas are used to calculate the callmap for previous versions. Since `hrtime()` wasn't removed, it should still be in Callmap.

**Comment by weirdan** [comment]
> The FunctionCallReturnTypeFetcher.php file seem to return the same structure as detailed in Callmap so I removed it

The difference seems to be the `from_calculation` flag. I'm not sure what's its intended meaning and how that affects inference, but it's used in several places in the codebase.

**Comment by orklah** [comment]
> 
> 
> > so I removed it from Callmap
> 
> You shouldn't. Callmap contains the data for latest and greatest supported version, and deltas are used to calculate the callmap for previous versions. Since `hrtime()` wasn't removed, it should still be in Callmap.

oooh, I thought it was the base version and deltas were added on top. Thanks, I'll fix this

**Comment by orklah** [comment]
> The difference seems to be the `from_calculation` flag. I'm not sure what's its intended meaning and how that affects inference, but it's used in several places in the codebase.

IIRC, from_calculation is used to allow some operations on the result type. For example:
`$a = (int) PHP_INT_MAX;` is a redundantCast but `$a = (int) PHP_INT_MAX + 1;` is allowed because the calculation may have changed the type
It's the trick we used for allowing string cast from string offset keys that could have been implicitly casted to int by php

I'm pretty sure it's used here to be able to do a `is_float` on the result while still declaring the type is `int` for some reason

**Comment by orklah** [comment]
I'll close this PR because the issue is not on data sources. If someone stumble here on the future, there is still some small weirdness here and there:
- callmap declare the function can return false but there is no trace of this in FunctionCallReturnTypeFetcher. This should probably be added with a ignoreFalsableIssues flag
- The param name is wrong in callmap_73 (should be `as_number`)
- The `$int = Type::getInt(); $int->from_calculation = true` is weird, it's the only place in the code where we use it given that this is the first parameter of `getInt()`. This could (should?) be replaced by `$int = Type::getInt(true);`

**Comment by kelunik** [comment]
It can only return `false` if it's not available on the given platform and it's a compile time decision.

https://github.com/php/php-src/blob/a06c20a17c97a76956f3454291ba0a46ee39eda1/ext/standard/hrtime.c#L183

**Pull request closed without merging**
