### PR TITLE
chore(ci): update psl version used in e2e tests

### PR DESCRIPTION
**Pull request by azjezz**
closes #6706

### CODE REVIEW

**Comment by muglug** [comment]
Sorry @azjezz just realised I invited you to `muglug/psl` not `psalm/endtoend-test-psl`

**Comment by azjezz** [comment]
Thanks @muglug 

@orklah build is passing, except for missing label.

**Comment by orklah** [comment]
@azjezz cool! Can you rebase and add https://github.com/vimeo/psalm/commit/73b5c9fb41bd812043522baf76ac06a7636ce60b back again?

**Comment by azjezz** [comment]
rebased!

**Comment by azjezz** [comment]
PSL 2.0 has standard project structure, but i think we should wait before switching to 2.0 as it requires PHP 8.1

**Comment by orklah** [comment]
Well, there's no issue running the CI on 8.1 to test real projects. However, we're based on a fork of psl so in any case, we won't always run against the most up-to-date branch anyway

**Pull request merged**
