### PR TITLE
Switch to amp v3

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by weirdan** [comment]
Is this something for Psalm 6?

**Comment by danog** [comment]
Yep, it seems like it, since we're raising the minimum version

**Comment by danog** [comment]
@orklah Do you think you could make another branch for v5 just like we did for v4?
I don't have any clear ETA for v6, but at least this way people that have dependency conflicts due to amp will be able to require the dev-master branch, instead (and I could also send in some PRs to remove stuff that was planned for deprecation in v6).

**Comment by danog** [comment]
Addendum: I don't have any clear date for v6 in mind, but I would prefer we avoid prolonging the release like we did last time, it's no big deal to make majors once or twice a year IMO :)

**Comment by danog** [comment]
Should be good to merge!

**Pull request merged**
