### PR TITLE
Fix Incompatible types found for T (Stub&ProxyQueryInterface is not in ProxyQueryInterface&Stub)

### PR DESCRIPTION
**Pull request by VincentLanglet**
I tried this on my project and
- my issue was solved.
- I saw no extra errors.

Closes https://github.com/vimeo/psalm/issues/7825

### CODE REVIEW

**Comment by orklah** [comment]
I'm not sure about that one. It fixes the issue because the check was made by checking if the type display is the same, so when you fix the display, it just sweep the dust under the rug, but the issue with the suboptimal check is still there and the structural issue with intersections not behaving the same way when turned the other way around is still there too

**Comment by AndrolGenhald** [comment]
Yeah, I agree with @orklah, I know we use IDs for type equality checks sometimes but it doesn't seem like a great idea. There's also `Union::equals` but that doesn't do what you'd expect either. I think for now the best solution is to change it to 2 `UnionTypeComparator::isContainedBy` checks, checking that each type is contained by the other.

**Comment by VincentLanglet** [comment]
> I think for now the best solution is to change it to 2 `UnionTypeComparator::isContainedBy` checks, checking that each type is contained by the other.

I updated the PR then

**Comment by VincentLanglet** [comment]
Is it ok like this @orklah ? :)

**Comment by orklah** [comment]
Looks good!

Can you add your snippet in tests please?

**Comment by VincentLanglet** [comment]
> Looks good!
> 
> Can you add your snippet in tests please?

Sure ! ... but in which file ?

**Comment by orklah** [comment]
ClassTemplateTest should be fine :)

**Comment by VincentLanglet** [comment]
> ClassTemplateTest should be fine :)

Done :)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
