### PR TITLE
assert that some type is a list

### PR DESCRIPTION
**Pull request by orklah**
will fix an item of #6395

### CODE REVIEW

**Review by weirdan — COMMENTED** [review]
I wonder whether a stub would not suffice here. E.g.
```php
/**
 * @psalm-assert-if-true list<mixed> $array
 */
function array_is_list(array $array): bool {}
```

**Comment by orklah** [comment]
Possibly, but string, bool, array, object are all handled here. I think having it here is less confusing.

We could do another PR if we want to migrate everything to stubs though... Or if you want I can migrate all of them in this PR

**Comment by weirdan** [comment]
Consistency is good, so it should be ok the way it is. Just curious, how hard would it be to use FQNs instead of local names? Because right now Psalm doesn't understand namespace-local overrides of global predicates: https://psalm.dev/r/8d7345506e c.f. https://3v4l.org/4Pko7

**Comment by orklah** [comment]
Oh, this is kinda bad (I'd not feel bad about the fool who did override those with another meaning though!). I wonder if this is fixable in assertions, I'll check

**Comment by orklah** [comment]
There's probably a better way to check whether we're using the base function, but I couldn't find it!

**Comment by orklah** [comment]
I'll have to check why CI is failing, I'd not expected that

**Comment by orklah** [comment]
the CI was failing because I didn't handle the namespace fallback. It's now OK

**Pull request merged**
