### PR TITLE
Modernize strpos() calls

### PR DESCRIPTION
**Pull request by jack-worman**
Ran php-cs-fixer rule [modernize_strpos](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/alias/modernize_strpos.rst)

### CODE REVIEW

**Comment by jack-worman** [comment]
Not sure why the phar build is failing since `symfony/polyfill-php80` is a require dependency.

**Comment by weirdan** [comment]
> Not sure why the phar build is failing

The code in question is being run before any autoloader is registered. 

> Also, does not happen when I build the phar locally.

You need to run `psalm.phar --version` on PHP 7.4 to reproduce it.

Overall I don't think we need this PR just yet. Possibly we can drop the polyfill too, as it was introduced in a 'revert' commit, so it's probably not really used.

**Comment by jack-worman** [comment]
> Possibly we can drop the polyfill too, as it was introduced in a 'revert' commit, so it's probably not really used.

I see the `\Stringable` interface being used.

**Comment by weirdan** [comment]
> I see the \Stringable interface being used.

Indeed, missed that.

**Comment by orklah** [comment]
This would be easy to remove though, as Stringable is implied when __toString is there

**Comment by weirdan** [comment]
@danog is there any reason you added explicit `implements Stringable`?

**Comment by danog** [comment]
Naah, no specific reason, just wanted to make it explicit and at the time I was hoping to raise the minimum psalm php version to 8.0 :)

**Pull request closed without merging**
