### PR TITLE
cache statements even without persistent parser cache

### PR DESCRIPTION
**Pull request by vognev**
Attempt to improve performance issue reported in #7873

### CODE REVIEW

**Comment by orklah** [comment]
Looks great!

Can you take a look at failures on the "Run Shepherd / build (pull_request)" job? (You can ignore the two first errors, I need to fix those)

**Comment by orklah** [comment]
Great! Thanks!

**Comment by M1ke** [comment]
I am wondering if this is the change responsible for a change of behaviour I am seeing in 4.23.

When running 4.22 on our codebase (6840 PHP files) the result comes back with

```
Checks took 177.73 seconds and used 2,468.652MB of memory
Psalm was able to infer types for 89.8237% of the codebase
```

Whereas running 4.23 returns

```
Checks took 177.55 seconds and used 3,392.045MB of memory
Psalm was able to infer types for 89.8159% of the codebase
```

So a ~35% increase in RAM usage. Not suggesting this is definitely the cause, but from the items listed as released in 4.23 this does appear the obvious place where RAM usage might increase. @vognev I am interested if you saw any increased RAM usage when debugging after the fix (as I know you had used debug logs when investigating what needed fixing)?

**Comment by vognev** [comment]
in my testing, for my codebase (885 files analyzed), we benefited a lot in total time which inspection taken:

```
4.22

Checks took 425.14 seconds and used 517.665MB of memory
Psalm was able to infer types for 82.2386% of the codebase
```

```
55a45a9

Checks took 47.48 seconds and used 1,181.505MB of memory
Psalm was able to infer types for 82.2576% of the codebase
```


```
4.23

Checks took 48.66 seconds and used 1,181.594MB of memory
Psalm was able to infer types for 82.2576% of the codebase
```

yes, used memory amount increased, but caching always needs some memory
on another hand, cache added in `55a45a9`, could contain some means
for controlling it's max size, but i've not found reliable and efficient way for
measuring single variable memory footprint

**Comment by M1ke** [comment]
I have a thought about using a pre-pass to assess what cache hits are likely, and only caching things that will be hit more than once, but potentially that'd just confuse things.

I think I need to see the impact of this on the psalm 5 alpha before I think about whether I'd like to offer a change to disable the caching via a config option.

**Comment by vognev** [comment]
well, i can propose only following improvement then - https://github.com/vognev/psalm/commit/cc4d6350cd9b6b2e8a149523518e90ab796f6a93

it will cache up to 32 heaviest statements, still not memory-constrained though

**Comment by M1ke** [comment]
That looks pretty sharp, I'll run it on our codebase and see what it can
manage. Thanks!

**Pull request merged**
