### PR TITLE
Convert LDAP resources to objects

### PR DESCRIPTION
**Pull request by tomasnorre**
Resolves: #6405 

I'm honestly in doubt regarding the `'link_identifier'=>'resource'` and `'result_identifier'=>'resources'` if they should be `LDAP\Connection` and `LDAP\Result` respectively?

### CODE REVIEW

**Comment by tomasnorre** [comment]
The unit tests are failing with cases like this. 

```
1) Psalm\Tests\Internal\CallMapTest::testOutgoingSignaturesMustMatchMostRecentIncomingSignatures
Outgoing signatures in CallMap_81_delta.php don't match corresponding incoming signatures in CallMap_historical.php
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'ldap_first_attribute' => Array (
         0 => 'string|false'
         'ldap' => 'resource'
-        'result' => 'resource'
+        'entry' => 'resource'
     )
     'ldap_first_entry' => Array (...)
     'ldap_first_reference' => Array (...)
````

But I cannot see what I have done wrong reading the code nor the error message. Could some one give me a pointer?

**Comment by orklah** [comment]
Check at the arguments names :). You have to keep consistence all the way from the Callmap.php, through each delta file and when all deltas are applied, you should be left with Callmap_historical. If you changed names, then either the names changed in PHP itself and this should be reflected by a change in a delta file, or the name was wrong in Psalm all the way and you have to change the Callmap_historical too. (note that the names were not important before PHP 8.0 so no need to do research about the internal name before that. If it has not changed in PHP 8.1, change the historical file too)

**Comment by tomasnorre** [comment]
Thx will look into that. How do I confirm "problems" like this? As I have no rendered PHP Manual for 8.1 yet.

**Comment by orklah** [comment]
Looking at the PR in php-src, I remembered they have their own stubs now: https://github.com/php/php-src/pull/6963/files#diff-e4f76e193517f1144ea18d65617548c3b98809ad5b575b8cc38b708de00233ac

You should be able to find what you're looking for in here

**Comment by orklah** [comment]
Same here, could you rebase?

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
