### PR TITLE
Nullsafe calls should not trigger NPE on consecutive calls 

### PR DESCRIPTION
**Pull request by orklah**
This should solve #4523

I'm sure this is not the best way to do that but it seems to do well enough.

One side effect I could foresee is if `baz()` can return null in `$a?->baz()`, then a potential NPE won't be reported on `$a?->baz()->bar()` anymore

### CODE REVIEW

**Comment by muglug** [comment]
Is this still caught correctly?

```php
<?php

interface Bar {
    public function doBaz(): void;
}
interface Foo {
    public function getBar(): Bar;
}
function fooOrNull(): ?Foo {
    return null;
}
$a = fooOrNull()?->getBar();
$a->doBaz();
```

**Comment by orklah** [comment]
No, it's not caught anymore. After this PR, Psalm would effectively treat any null value from a nullsafe call as "acceptable". 

If we wanted to do better, I guess this would need a new flag on the union `nullsafe_shortcircuit` that would be treated independantly from the null value inside the Union and that would disable NPE only in the current expression. I guess we would have to reset this new flag at the end of each expression.

**Comment by muglug** [comment]
I think this is an AST-sensitive thing, not a type-sensitive thing — we need to add (and remove where necessary) an `->inside_nullsafe` flag on the Context object

**Comment by muglug** [comment]
Oh actually sorry I think your solution is better, and assignments would remove that flag from the type. Icky, but the actual implementation is icky IMO

**Comment by muglug** [comment]
Fixed in f3fc112ba

**Comment by muglug** [comment]
I went with the AST way, which is I think how PHP itself behaves

**Comment by orklah** [comment]
Oh great! Thanks for fixing that :)

**Pull request closed without merging**
