### PR TITLE
Allow config to define thread count (4.x)

### PR DESCRIPTION
**Pull request by M1ke**
Applying the same commits from https://github.com/vimeo/psalm/pull/7442 to the 4.x branch

### CODE REVIEW

**Comment by M1ke** [comment]
As mentioned here (https://github.com/vimeo/psalm/pull/7442#issuecomment-1026056111) if this gets merged to 4.x I am happy to resolve any conflicts with master, but I believe it should fit in directly.

**Comment by M1ke** [comment]
I can see that the check `ci/circleci: test-with-real-projects` fails and it's hard to see what in this branch would cause this - nothing in this work would change how Psalm carries out its analysis, and it will only apply the thread limit if the config file is modified.

**Comment by orklah** [comment]
failures in real projects are indeed unrelated :)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
