### PR TITLE
Fix array<empty, empty> not in array{foo?: mixed}<string, mixed>

### PR DESCRIPTION
**Pull request by VincentLanglet**
Trying to fix https://github.com/vimeo/psalm/issues/4963
I tried to modify my vendor and this seems to fix the issue but there is certainly some improvements.

I'm not familiar at all with the different types.
Should I do something with `List` too ? Is there an easier way to check for empty array ?

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I can't decide if I should create a new file for the test or add one to an existing file ; any thought @muglug ?

**Comment by muglug** [comment]
Merge/rebase master, where you'll find a `tests/TypeComparatorTest.php` with a place to slot yours in.

**Comment by VincentLanglet** [comment]
Thanks @muglug, it works well. Test are failing without my fix. It's ready to be reviewed/improved :)

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
