### PR TITLE
Added Hook\AfterCodebasePopulatedInterface

### PR DESCRIPTION
**Pull request by weirdan**
It could be used to perform operations after files have been scanned, but before main analysis is started.

### CODE REVIEW

**Comment by muglug** [comment]
Mind adding a test or two?

**Comment by weirdan** [comment]
Oh, it's missing the registration part. Gonna add this in a moment.

**Comment by muglug** [comment]
Looks like a problem with the 7.4 snapshot and PHPUnit :/

**Comment by weirdan** [comment]
Yeah, I've seen bugs reported about anonymous classes causing crashes in 7.4

**Pull request merged**
