### PR TITLE
Remove ReflectionType::getName(), move ReflectionType::isBuiltin()

### PR DESCRIPTION
**Pull request by weirdan**
* `ReflectionType::getName()` was never there: https://3v4l.org/1iZt4
* `ReflectionType::isBuiltin()` was moved to `ReflectionNamedType::isBuiltin()` in PHP 8

Fixes vimeo/psalm#5089

### CODE REVIEW

**Comment by weirdan** [comment]
CircleCI failure seems unrelated

**Comment by orklah** [comment]
> CircleCI failure seems unrelated

Are you sure? It seems pretty close:
> Method ReflectionType::getName does not exist

**Comment by weirdan** [comment]
@orklah There was a different failure before I restarted the build job.

**Comment by weirdan** [comment]
Current failure is legit as the code in question fails with methods returning union types: https://3v4l.org/8gt34E
This is already fixed in original package: https://github.com/Ocramius/ProxyManager/commit/13c118e77b927a56c06fe7824e921954c8261a93

**Comment by muglug** [comment]
Thanks, I'll update my fork of that

**Pull request merged**
