### PR TITLE
Add possibility to include xml config located in subdirectory

### PR DESCRIPTION
**Pull request by gmessier**
Fix the config.xsd file to accept "xml:base" attribute in tags and be able to include partial configuration located in another directory then the main configuration file.

### CODE REVIEW

**Comment by orklah** [comment]
Can you try to rebase? I don't reproduce the CI failure with master

**Comment by gmessier** [comment]
@orklah , with the departure of @muglug, do you know what is the flow for PRs to be merged and the release management process? I see many PRs that seems ready to be merged (many from you). Comment in this PR is probably not the right place to talk about that, but I didn't found a best place.

**Comment by orklah** [comment]
@gmessier currently, both @weirdan and me have merging rights. We're still trying to see how we can work this out given our available time and knowledge of Psalm.

Except for small and safe PR, I avoid merging my own PR, especially when they're structural or complex(like those I authored and who are ready to be reviewed). However, I have had a lot more time available than @weirdan recently, that's why there's a lot of them waiting right now.

Last week, I merged PR where I was confident enough of the content and where I was sure @weirdan had the opportunity to look at. I'll wait a little before merging this so he can take a look (especially since I have no particular knowledge of xml). As time passes, I think we'll get more confident(and hopefully, find some fellow contributors) and know when we can merge PR, but right now it can take some time, sorry for that.

About releases, they're made by @weirdan currently when there's a need. It's possible we'll end up doing them less frequently in hope to get more feedback pre-releases to avoid breaking things.

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
