### PR TITLE
Don't output console links in CI env

### PR DESCRIPTION
**Pull request by weirdan**
They are all but useless there, and are actually causing an issue with GHA output.

Fixes vimeo/psalm#7047

### CODE REVIEW

**Comment by weirdan** [comment]
Test failure is legit, but not being able to rely on superglobals makes it quite a bit harder.

**Review by orklah — APPROVED** [review]

**Comment by drupol** [comment]
Thanks for fixing the issue !

Question:Could we consider using https://packagist.org/packages/ondram/ci-detector for checking if it is running in CI ?

**Comment by orklah** [comment]
Yeah, we could consider it if needed. Do you happen to use an exotic CI environment?

**Comment by drupol** [comment]
On my side no, I only use Github and Gitlab.

**Comment by drupol** [comment]
That said, that package support quite a large amount of CI system that I was not even aware of !

**Comment by orklah** [comment]
That was kinda my point, if we weren't aware they existed, it will be the case for most people too :)

If we have a feedback from a user, we'll consider making the change, but I try not to add dependencies for things I'm not sure are needed

**Pull request merged**
