### PR TITLE
Fix composer warnings

### PR DESCRIPTION
**Pull request by weirdan**
These two classes weren't autoloadable because their FQCNs didn't match
the file paths.

### CODE REVIEW

**Comment by edsrzf** [comment]
Oops, sorry about that. Seems like something that CI could have caught somewhere?

**Review by orklah — APPROVED** [review]

**Comment by weirdan** [comment]
`composer dump-autoload --strict-psr` should do the trick

**Comment by weirdan** [comment]
> Oops, sorry about that. Seems like something that CI could have caught somewhere?

It kinda did (BCC was failing) but nobody bothered to check its output because the PR was targeting the master branch where BC breaks are allowed.

**Pull request merged**
