### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by TysonAndre**

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by iluuu1994** [comment]
Shouldn't we adjust the config so that this is caught by CI?

**Comment by muglug** [comment]
They should have been caught in CI - I need to fix three bugs: #1899, #1900, #1901

**Comment by iluuu1994** [comment]
Ah I see

**Comment by muglug** [comment]
and those are now fixed

**Pull request merged**
