### PR TITLE
Implement @psalm-trace annotation, fixes #3079

### LINKED ISSUE #3079: @psalm-trace to show what the analyzer is thinking at particular point in code
Would it be possible to add an annotation `@psalm-trace $x` that would output the inferred type of `$x` to the stdout when running static analyzer?

Something like

```
function f(int $x) {
    /** @psalm-trace $x */
    $y = $x . 'a';
}
```

```
function.php:323 $x: int
```

Thank you!

### PR DESCRIPTION
**Pull request by m0003r**
I have same thoughts about `@psalm-trace` as in #3079 , so I just implemented is as simple as it possible.

Have I done it correctly?

### CODE REVIEW

**Comment by muglug** [comment]
Very nice, thanks!

**Comment by weirdan** [comment]
@m0003r outputting things directly will break most structured reports (xml, json, etc). It already breaks on psalm.dev when using `@psalm-trace`: https://psalm.dev/r/d9107243d3

I would suggest emitting a special kind of issue instead.

**Comment by m0003r** [comment]
@weirdan oh, I haven't thought about it, I'll do it soon.
Only one question: which `ERROR_LEVEL` should have that special issue?

**Comment by weirdan** [comment]
Lowest possible, I suppose. You don't want to break CI builds if you left the annotation in the source code accidently.

**Comment by m0003r** [comment]
@weirdan did it in #3106

**Pull request merged**
