### PR TITLE
Introduce `DuplicateProperty` issue

### PR DESCRIPTION
**Pull request by tuqqu**
Emit a `DuplicateProperty`, whenever a class property (either instance or a static one) is defined twice.

### CODE REVIEW

**Comment by tuqqu** [comment]
@orklah do you know why `Run Shepherd` failed? Seems unrelated.

**Comment by orklah** [comment]
Build is broken on master since last merge. There has been a discussion here: https://github.com/vimeo/psalm/pull/10209#issuecomment-1750806540 not sure what's going on

**Comment by robchett** [comment]
I've added a hotfix for the build errors https://github.com/vimeo/psalm/pull/10268 and raised https://github.com/vimeo/psalm/issues/10267 to track the source.

**Comment by tuqqu** [comment]
@robchett thanks, rebased the branch on the new master

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
