### PR TITLE
Fix array_unique callmap

### PR DESCRIPTION
**Pull request by othercorey**
refs https://github.com/vimeo/psalm/issues/7956

The array element must be stringable regardless of sort type.

### CODE REVIEW

**Comment by weirdan** [comment]
> The array element must be stringable regardless of sort type.

Shouldn't we accept non-stringable objects when `SORT_REGULAR` is used? It seems to work: https://3v4l.org/BLlbI

**Comment by othercorey** [comment]
I was getting string conversion errors when testing. Will take a closer look.

**Comment by othercorey** [comment]
Guess I had that test disabled when doing some of this. I'll move this to this stubs as was going to originally then.

**Comment by othercorey** [comment]
@weirdan This does not seem to throw errors when using an array like `[(object)[], 1]`, any ideas? Does psalm not determine a union type for array values?

```php
/**
 * @psalm-pure
 *
 * @psalm-template TValue
 *
 * @param array<TValue> $array
 * @param (TValue is (\Stringable|string|int|float|bool|null) ? (0|1|2|5) : 0) $flags
 *
 * @return array<TValue>
 */
function array_unique(array $array, int $flags = SORT_STRING): array
{
}
```

**Comment by weirdan** [comment]
>  Does psalm not determine a union type for array values?

It does. The problem, I suspect, is in the handling of conditional types in `@param` - it's not the most polished part of Psalm code.

**Comment by othercorey** [comment]
Can you point me to that area of the code? Maybe there's some clear logic errors.

**Comment by weirdan** [comment]
It should be happening somewhere around `src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php`, I suppose. Fair warning: template handling in Psalm is not for the faint of heart.

**Comment by othercorey** [comment]
It seems like the array element type just gets merged into `mixed`, but don't know if that's just at the point of tracing:

https://psalm.dev/r/c2dbbe4982

**Comment by othercorey** [comment]
@weirdan For now, reduced this to just fixing the array_unique() callmap and will have to tackle the stubs issue separate. Unmarked this PR as fixing the original issue.

**Comment by weirdan** [comment]
Note that there is a return type provider for `array_unique` which may override both callmap and stubs.

https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayUniqueReturnTypeProvider.php

**Comment by othercorey** [comment]
@weirdan I went back to the original commit for the array_unique return provider. It wants to preserve a non-empty array types (there were fixes to it in the history as well). This should be do-able with templates and re-added the stub along with missing tests. What do you think?

https://github.com/vimeo/psalm/commit/38de68f5079ac45a3a6f17d63091a4271c0819af#diff-0782323bf242be8068800ab7ffdd467b06492b5e60ff4ef2094673de4e9bcff9

**Comment by othercorey** [comment]
@weirdan If you don't want to go this route with array_unique, we can close it.

**Comment by weirdan** [comment]
> If you don't want to go this route with array_unique, we can close it.

I just didn't have the time and energy to review it. All maintainers are volunteers here, and we do it in our spare time. I want to keep this project rush-free, or it would feel like an unpaid job.

**Comment by othercorey** [comment]
> > If you don't want to go this route with array_unique, we can close it.
> 
> I just didn't have the time and energy to review it. All maintainers are volunteers here, and we do it in our spare time. I want to keep this project rush-free, or it would feel like an unpaid job.

Well then I apologize for making it feel rushed. In large projects, sometimes reviews are passed on by simply not merging so I was going to free up your time to not have to keep analyzing.

You are all doing an excellent job with a difficult project especially with reviews and feedback.

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
