### PR TITLE
Fix #8806

### LINKED ISSUE #8806: uncaught TypeError when calling array_map will null callback and non-empty array
The following works in 4.30 but throws a TypeError in 5.0

`array_map(null, [1]);`

Error from psalm.dev:
```
Internal Psalm error on line 101 - /vendor/vimeo/psalm/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayMapReturnTypeProvider.php: Psalm\Internal\Provider\ReturnTypeProvider\ArrayMapReturnTypeProvider::Psalm\Internal\Provider\ReturnTypeProvider\{closure}(): Argument #1 ($sub) must be of type array, Psalm\Type\Union given
```

`array_map(null, []);` runs without exception.

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by orklah** [comment]
Thanks!

**Comment by weirdan** [comment]
https://psalm.dev/r/fd479a295e - it still fails on psalm.dev

**Comment by orklah** [comment]
phar build seems broken, it doesn't launch. Maybe related to failed CI?

**Comment by weirdan** [comment]
>  it doesn't launch

Doesn't it? I see a non-crashing run right here in this ticket: https://app.circleci.com/pipelines/github/vimeo/psalm/10128/workflows/d1c6c5c6-09e3-49ca-bd07-e0656013a83d/jobs/35716

**Comment by orklah** [comment]
Yeah but there's no artifact. Also, the CI on master branch says "Build phar / build-phar (push) Skipped"

**Comment by weirdan** [comment]
`psalm.phar` artifact is produced in a previous job (of the same workflow): https://app.circleci.com/pipelines/github/vimeo/psalm/10128/workflows/d1c6c5c6-09e3-49ca-bd07-e0656013a83d/jobs/35715/artifacts

GH Actions build-phar.yml could be skipped if there are duplicate jobs running (because they would fail to push the results to `psalm/phar`): https://github.com/vimeo/psalm/blob/master/.github/workflows/build-phar.yml#L15-L29

**Comment by weirdan** [comment]
Anyway it won't affect psalm.dev as we don't run phar there as far as I know.

**Comment by orklah** [comment]
I thought it did for running psalm. 

Anyway, Psalm.dev is running with commit c3cc906 which is outdated (but I'm not sure why now...)

**Comment by weirdan** [comment]
@muglug can you check why `vimeo/psalm` does not get updated on psalm.dev? I don't think anyone else can do that.

**Comment by muglug** [comment]
Ah I've bumped this now

**Pull request merged**
