### PR TITLE
Update return type of iterator_count and iterator_apply functions to 0|positive-int

### PR DESCRIPTION
**Pull request by ricardoboss**

### CODE REVIEW

**Comment by orklah** [comment]
Can you please rebase on 4.x? commits on master will only be released in Psalm 5

**Comment by ricardoboss** [comment]
Should I reopen the PR targeting the `4.x` branch?

**Comment by orklah** [comment]
You should follow those steps:
1) `git rebase -i upstream/4.x` (assuming your remote for this repo is named upstream)
2) resolve any conflict git tells you to (I don't expect any here)
3) once it's done `git push --force`
4) Come back here and next to the title of your PR, click on Edit and you'll be able to change the target of your PR to match with your rebase

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
