### PR TITLE
Plugin example: dynamic class suppression based on interface implementation

### PR DESCRIPTION
**Pull request by ludofleury**
@see https://github.com/vimeo/psalm/issues/4684

### CODE REVIEW

**Comment by ludofleury** [comment]
Do we fix example ? :)

**Comment by muglug** [comment]
Thanks, I've added this example to documentation here: https://github.com/vimeo/psalm/blob/master/docs/running_psalm/dealing_with_code_issues.md

**Comment by muglug** [comment]
I don't think it's necessary to have the actual code in the `examples` directory

**Comment by weirdan** [comment]
Using reflection is an antipattern in SA context though. There are `Codebase::classExists()` and `Codebase::classImplements()` methods that do not execute actual application code, unlike `class_exists()` and `ReflectionClass`.

**Pull request closed without merging**
