### PR TITLE
Introduce `value-of` with backed enum cases in assertions

### PR DESCRIPTION
**Pull request by boesing**
Fixes assertion inconsistencies as described in here:

https://psalm.dev/r/8e09e2bfb4

### CODE REVIEW

**Comment by boesing** [comment]
PR is ready for review, GHA just failed installing composer in windows unit test 1 chunk.

**Comment by orklah** [comment]
Thanks <3!

**Comment by weirdan** [comment]
@boesing it looks like the feature wasn't implemented as it was intended. Can you confirm if the following were your intentions:
1. `@psalm-assert AEnum::A|AEnum::B $param` should **not** be the same as `@psalm-assert value-of<AEnum::A|AEnum::B> $param` (because otherwise `value-of` would be useless here)
2. `@psalm-assert value-of<AEnum::A|AEnum::B> $param` should be the same as `@psalm-assert value-of<AEnum::A>|value-of<AEnum::B> $param`
3. `value-of<AEnum::A>` should produce the backing type (e.g. `string` or `int`, or a literal string or int) and not the case type (essentially an object of type `AEnum`)

**Comment by weirdan** [comment]
Snippet for the above list: https://psalm.dev/r/0eb3427541

**Comment by boesing** [comment]
@weirdan As already mentioned in #10082, that was ofc not intended and I am aware that value-of should result in a different result than the values without.

Seems that there were no test to verify the behavior and thus, it was dropped. I can see when I can find some time to fix that, but earliest would be this weekend.

**Comment by boesing** [comment]
Yes, thats how it is tested in the tests provided by this PR.
Seems there weren't any tests for the initial enum implementation and thus, that got most probably lost.
The only thing I did not tested explicitly was `@psalm-assert value-of<AEnum::A>|value-of<AEnum::B> $param` but I guess that would work the same way.

**Pull request merged**
