### PR TITLE
Forbid template annotation on closures

### PR DESCRIPTION
**Pull request by weirdan**
They don't work properly anyway.

Fixes vimeo/psalm#5472

### CODE REVIEW

**Comment by weirdan** [comment]
Apparently people use them.

/cc: @azjezz

**Comment by azjezz** [comment]
I'm pretty sure hack does support generics in closure ( () => {} syntax, not php closure syntax since that is "deprecated", hence why generics weren't added there ).

**Comment by azjezz** [comment]
so technically, the code that is currently failing in PSL, would pass in Hack if i remove all parameter types, as the type checker would get that it is generic ( even tho not explicitly ), but this would result in an error in psalm.

i personally like having support for generic in closures ( even variables/constants, see https://github.com/vimeo/psalm/issues/3963 )

**Comment by weirdan** [comment]
How do you know it's actually generic and not just untyped?

**Comment by azjezz** [comment]
It's not untyped, hack detects the type automatically depending on the usage of the closure.

e.g:
a

if we add `$c(vec['a', 'b', 'c'], 'c');` under `$c(vec[1, 2, 3], 3);`, it becomes:

b


and it can't be un-typed since hack doesn't allow thing to be un-typed ( at least at the strictest level )

---

so if psalm is to remove generics, it needs to add the ability to automatically detect type of callables without having to specify them based on usage.

**Comment by azjezz** [comment]
hm, actually, looking at it, i think the failed case in psl can be fixed without using generics in closure, however, i still need to specify the type: https://psalm.dev/r/65b9344e48

here's a re-implementation with hack that passes: 

image

**Comment by azjezz** [comment]
okay, all PSL issues have been fixed in https://github.com/azjezz/psl/pull/176, i think the "detect callable type based on usage" feature can be tracked in another issue.

**Comment by muglug** [comment]
@azjezz @weirdan I've updated my fork!

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
