### PR TITLE
Fix absolute stub path on windows too

### PR DESCRIPTION
**Pull request by ArSn**
Relates to PR #2883 / issue #1331. - now this should work on windows too :)

### CODE REVIEW

**Comment by muglug** [comment]
Mind rebasing this onto master?

**Comment by ArSn** [comment]
certainly, not sure how I made that happen - sorry!

**Comment by ArSn** [comment]
> The command "phpenv global 7.3" failed and exited with 1 during .

Hmm, issue with travis rather than the code on this PR?

**Comment by muglug** [comment]
Yeah, Travis is occasionally flaky

**Pull request merged**
