### PR TITLE
Performance only load files once

### PR DESCRIPTION
**Pull request by kkmuffme**
Fixes https://github.com/vimeo/psalm/issues/8008

Speeds up psalm between 5-15%.

Also fixes an issue on Unix systems where A.php and a.php were treated equal, even though they are different files, since unix file names are case sensitive.

### CODE REVIEW

**Comment by AndrolGenhald** [comment]
Can you double check memory usage? I'd expect the parsed structures to be much bigger than file contents, but this will definitely increase memory usage and it wouldn't be bad to double check. I assume this code is bypassed for the language server, but that would be good to verify as well.

**Comment by kkmuffme** [comment]
The memory usage depends on what you are checking, as the memory usage is directly proportional to the number and size of files analyzed.

If real world tests show that memory consumption is too high, we could offer an option to 
a) limit the number of files that stay "cached" or 
b) only "cache" specific types (e.g. stubs)
c) exclude certain files from "cache"

I tested it on the WP core repo and the memory usage was only slightly higher than before.

**Comment by AndrolGenhald** [comment]
Yeah, that's what I expected, just wanted to confirm with an actual test.

I do want to double check how the language server works though. If the language server relies on this class then the caching could completely break it, unless it's only used to get initial file state in which case the cache is just wasting memory.

**Comment by kkmuffme** [comment]
Could someone merge this?

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
