### PR TITLE
Xpath injection #10162

### PR DESCRIPTION
**Pull request by cgocast**

### CODE REVIEW

**Comment by cgocast** [comment]
IMHO, the results of the backward compatibility tests are not very relevant for the change I made. The tests spot a breaking change for psalm internal class TaintKind, which is not meant to be directly used by psalm plugins.

If someone disagrees with me, I'll be glad to make the necessary changes if he gives me a hint on how to do it.

**Comment by weirdan** [comment]
> The tests spot a breaking change for psalm internal class TaintKind,

It's not internal though.

>  I'll be glad to make the necessary changes if he gives me a hint on how to do it.

Target `master` (future Psalm 6). It's ok to have BC breaks in that branch.

**Comment by cgocast** [comment]
> > The tests spot a breaking change for psalm internal class TaintKind,
> 
> It's not internal though.
> 
> > I'll be glad to make the necessary changes if he gives me a hint on how to do it.
> 
> Target `master` (future Psalm 6). It's ok to have BC breaks in that branch.

Thank you @weirdan for your advice. I changed the target branch accordingly.

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
