### PR TITLE
Fix enum crash

### PR DESCRIPTION
**Pull request by AegirLeet**
Fixes https://github.com/vimeo/psalm/issues/10560.

First commit fixes the crash.

Second commit fixes the `InvalidEnumCaseValue` revealed once the crashing is fixed.

Third commit adds two test cases for the crash fix.

I'd like to add some more test cases to validate the value is resolved correctly, but not sure where.

### CODE REVIEW

**Comment by weirdan** [comment]
Does https://psalm.dev/r/38dc5a68ea (referencing the enum below rather than above) work with your PR?

**Comment by AegirLeet** [comment]
No, that still fails. Looks like the `ClassLikeStorageProvider` doesn't know about `SomeEnum` at that point. This seems to be a general issue with enums referencing things declared later. Seems to work fine with two classes and `const`s though (https://psalm.dev/r/5d409f074e).

I can look into it, but probably not before monday.

**Comment by AegirLeet** [comment]
@weirdan Is this still needed with https://github.com/vimeo/psalm/pull/10655?

**Comment by weirdan** [comment]
No, that PR addresses the issue you were trying to fix in a more general way.

**Pull request closed without merging**
