### PR TITLE
fix missing case for displaying varId

### PR DESCRIPTION
**Pull request by orklah**
This will fix https://github.com/vimeo/psalm/issues/6933

The message is a little weird because it says `Cannot access value on variable ARR` when it's a constant, but it's not a big deal.

Didn't add test because this is just a wording issue

### CODE REVIEW

**Comment by orklah** [comment]
This revealed a deeper bug where, if a constant have a varId, it is affected by assertions a weird way and this snippet https://psalm.dev/r/8c26aa0e98 produce an error because `DIRECTORY_SEPARATOR` somehow became mixed

**Comment by orklah** [comment]
Well, this is working. I'm not sure I like the fact that I had to call an Analyzer inside the Reconciler though, but I couldn't see a cache of global constants and I'm not sure we're supposed to create one...

**Comment by orklah** [comment]
Do you have thoughts about that @weirdan ?

**Comment by weirdan** [comment]
Looks good to me.

**Pull request merged**
