### PR TITLE
Support for properties in interfaces extending `\UnitEnum` & `\BackedEnum`

### PR DESCRIPTION
**Pull request by whatUwant**
Fixes https://github.com/vimeo/psalm/issues/7551

### CODE REVIEW

**Review by weirdan — APPROVED** [review]

**Comment by whatUwant** [comment]
For some reason the failed test was run on php 8.0
- [Linux](https://github.com/vimeo/psalm/runs/5293606761#step:7:195)
   ```
   tests/EnumTest.php
     PHPUnit 9.5.14 by Sebastian Bergmann and contributors.
     
     Runtime:       PHP 8.0.15
     Configuration: /home/runner/work/psalm/psalm/phpunit.xml.dist
     Random Seed:   1645557663
     
     ...................E.................                             37 / 37 (100%)
     
     Time: 00:17.389, Memory: 52.00 MB
     
     There was 1 error:
     
     1) Psalm\Tests\EnumTest::testValidCode with data set "InterfacesWithProperties" ('<?php\n\n                    ...      ', array(), array(), '8.1')
     Psalm\Exception\CodeException: NoInterfaceProperties - src/somefile.php:11:72 - Interfaces cannot have properties
   ```
- [Windows](https://github.com/vimeo/psalm/runs/5293606848#step:3:17)
   ```
   ==> Setup PHP 
   √ PHP Installed PHP 8.0.16 
   ```

It passes on PHP 8.1.3
```
$ vendor/bin/phpunit tests/EnumTest.php
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.3
Configuration: /psalm/phpunit.xml.dist
Random Seed:   1645559189

.....................................                             37 / 37 (100%)

Time: 00:04.850, Memory: 54.00 MB

OK (37 tests, 53 assertions)
```

**Comment by weirdan** [comment]
On PHP 8.0 Psalm seems to be unaware that `BackedEnum` is a descendant of `UnitEnum`, so your test fails due to 
```php
in_array('UnitEnum', $codebase->getParentInterfaces($fq_class_name/*="ExtendedBackedEnum"*/))
```
check.
Below is the list of parent interfaces for `ExtendedBackedEnum`, running on 8.1 and 8.0 respectively:
```
dap> $codebase->getParentInterfaces($fq_class_name) // PHP 8.1
array(2)
dap> 
  backedenum: "BackedEnum"
  unitenum: "UnitEnum"
dap> $codebase->getParentInterfaces($fq_class_name) // PHP 8.0
array(1)
dap> 
  backedenum: "BackedEnum"
```

**Comment by whatUwant** [comment]
Thanks for pointing it out. But I thought enum was available only since 8.1 
https://www.php.net/manual/en/language.enumerations.overview.php

**Comment by AndrolGenhald** [comment]
They're only available in 8.1, but I believe we're trying to support analyzing a project requiring PHP 8.1 while running PHP < 8.1.

This should be fixable in [stubs](https://github.com/vimeo/psalm/blob/4.x/stubs/Php81.phpstub#L3:L27), it looks like [BackedEnum](https://www.php.net/manual/en/class.backedenum.php) is supposed to extend [UnitEnum](https://www.php.net/manual/en/class.unitenum.php).

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
