### PR TITLE
fix: #10080

### PR DESCRIPTION
**Pull request by ging-dev**
Close: #10080 
cc @weirdan

### CODE REVIEW

**Comment by orklah** [comment]
@weirdan can you check this one? You seem to have identified a possible cause in the issue

**Comment by ging-dev** [comment]
> @weirdan can you check this one? You seem to have identified a possible cause in the issue

Test added, ready to merge

**Comment by orklah** [comment]
Thanks for the work! If you can rebase, I'll merge it :)

**Comment by ging-dev** [comment]
> Thanks for the work! If you can rebase, I'll merge it :)

my pleasure :)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
