### PR TITLE
Add support for resolving promises in Amp's coroutines

### PR DESCRIPTION
**Pull request by kelunik**
This is currently not fully working as intended, but mostly works. See comments for more information.

### CODE REVIEW

**Comment by muglug** [comment]
I'm not too keen on baking in support for a given implementation at a particular point in time.

But I am a fan of Amp, obviously, so I've added support for a `@psalm-yield` annotation that you can add to `Promise` – I've added it already to the stub that Psalm uses in af4a7ca.

**Comment by kelunik** [comment]
Thanks! I've had pretty much the same idea regarding the annotation.

**Comment by muglug** [comment]
The only downside is that things would be wrong in Psalm if yielding a `Promise` while not inside an `Amp` call, but 🤷‍♂

**Comment by kelunik** [comment]
@muglug Indeed, but I think anyone using Amp is fine with that risk compared to the value it provides. :+1:

**Comment by kelunik** [comment]
@muglug Unfortunately, yielding an `Amp\Promise<string>[]` results in the type being inferred as `Amp\Promise<string>[]`, so it's still `TValue == TSend` there. I'm not sure how that can be supported in a generic way. Should I open an issue?

**Comment by muglug** [comment]
Yes please

**Pull request closed without merging**
