### PR TITLE
[TASK] Resolve namespace of class related AST statements

### PR DESCRIPTION
**Pull request by ohader**
This change allows using `Class_` namespaces like in
PhpParser's original `NameResolver` implementation.

```
if ($node instanceof \PhpParser\Node\Stmt\Class_) {
   $fqcn = (string)($node->namespacedName ?? $node->name);
   $extents = (string)($node->extends->getAttribute('resolvedName'));
}
```

Corresponding parts have been duplicated and modified from
https://github.com/nikic/PHP-Parser/blob/v4.10.4/lib/PhpParser/NodeVisitor/NameResolver.php#L69-L81

### CODE REVIEW

**Comment by ohader** [comment]
Failing three shepherd tests are related to #5092

**Comment by weirdan** [comment]
CircleCI is currently down, but AppVeyor failure indicates a valid issue. `PhpParser\Node\Stmt\Class_` extends `PhpParser\Node\Stmt\ClassLike` that has `@property Node\Name $namespacedName ...`, yet Psalm fails to see that.

**Comment by weirdan** [comment]
Actually the same issue reported on shepherd build, and it's a false positive.

**Comment by ohader** [comment]
* rebased to recent `origin/master`
* misused `CodebaseTest` to reset corresponding namespace-related changes
* (hopefully) made CI services happy

**Comment by orklah** [comment]
@ohader Hi, I'm checking old PR, it seems this one was finished. I'm not sure I got what the goal was precisely though. Does it fixes something?

Could you rebase it please?

**Comment by ohader** [comment]
Without this change, namespaces for "ancestors" `extends ...` or `implements ...` were not resolved and would have to be retrieved individually when using custom event-handlers for instance. This change applies (some) of PhpParser's original `NameResolver` to Psalm's `SimpleNameResolver`.

The following screenshot shows the scenario without the change:

Screen Shot 2021-09-27 at 11 29 27

The following screenshot shows the scenario having the change applied - `resolvedName` is like in PhpParser's original `NameResolver` implementation:

Screen Shot 2021-09-27 at 11 33 37

**Comment by orklah** [comment]
Seems great :) I'll let @weirdan check but I think we can merge this then

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
