### PR TITLE
Mark finfo_open and finfo_file as impure

### PR DESCRIPTION
**Pull request by staabm**
https://psalm.dev/r/651cd68b91

### CODE REVIEW

**Comment by muglug** [comment]
Mind adhering to the < 120 characters-per-line rule?

**Comment by staabm** [comment]
> Mind adhering to the < 120 characters-per-line rule?

sorry, wasn't aware the codebase has such a rule.

the failed circle CI build does not show me a error message (can only see that it failed).

**Comment by muglug** [comment]
> the failed circle CI build does not show me an error message (can only see that it failed).

You have to click through – I believe the error message is public

Anyway, thanks!

**Comment by staabm** [comment]
I need to create a circle ci account by a login via github button. :-(

**Pull request merged**
