### PR TITLE
Errors in overwritten stub reported for function that overwrites

### PR DESCRIPTION
**Pull request by kkmuffme**
https://github.com/vimeo/psalm/issues/3249

This is not a fix, but just the code to reproduce the issue as requested.

### CODE REVIEW

**Comment by kkmuffme** [comment]
>If you know the parent function will return string, you're free to add that to your stub, at least in phpdoc, this should keep you from getting this

The issue is, that I have 1000s of functions with missing or too general phpdocs.

The issue basically is: why does psalm give me an error for a stub, when the function I declared (non-stub) is correct.

What would need to change is:
If a function is declared in code, it should always take priority over stubs.

**Comment by orklah** [comment]
I made some experiments with function stubbing:
- Psalm will enforce types and numbers of params of the stub instead of those of the declared function
- Psalm will trust phpdoc return type of the stub over the phpdoc return type of the declared function
- Psalm will trust signature return type of the stub over the signature return type of the declared function
- Psalm will trust signature return type of the stub over the phpdoc return type of the declared function
- If the stub has no type (in signature nor in phpdoc) Psalm will infer return type from the stub and trust that

I made limited tests but it appears to work about the same with methods instead of functions, with one exception:
- Psalm will emit an InvalidReturnType when a method doesn't have return statement but the parent stub was inferred as returning string instead of a MissingReturnType like it throws on functions

Overall, the behaviour seem coherent with what I'd expect of stubs, they're made to replace concrete implementation with different/more precise types. I guess we could throw an InvalidReturnType instead of MissingReturnType for functions too.

**Comment by orklah** [comment]
I tried to check, both errors are thrown by ReturnTypeAnalyzer::verifyReturnType. the difference is that this method receive a non-null $return_type (of `string`) for the method and null for the function.

I tried to look further but the way the return type is retrieved is quite different between the two and I didn't find an obvious path to tackle this.

I'm afraid I do not care this much for this bug as it happens for:
- incomplete stubs
- when the function is then found in the code
- with a documented return type for the function that do not match the statements in the function

I won't spend more of my time on this, though if you want to try to work on this, I'll gladly help you and give you pointers.

**Comment by kkmuffme** [comment]
Maybe a simple solution would be to give the actual code priority over any stubs? Perhaps as a configurable option?

So all this:
>Psalm will enforce types and numbers of params of the stub instead of those of the declared function
Psalm will trust phpdoc return type of the stub over the phpdoc return type of the declared function
Psalm will trust signature return type of the stub over the signature return type of the declared function
Psalm will trust signature return type of the stub over the phpdoc return type of the declared function
If the stub has no type (in signature nor in phpdoc) Psalm will infer return type from the stub body and trust that

Would be reversed, with phpdoc of the declared function having priority over stubs.

**Comment by weirdan** [comment]
> Maybe a simple solution would be to give the actual code priority over any stubs? 

Not going to happen. The main use case of stubs in Psalm is to override functions / methods / classes etc.

**Pull request closed without merging**
