### PR TITLE
Fix array_* function signatures

### PR DESCRIPTION
**Pull request by othercorey**
`array_replace` historically could return `null` on a type error, but that didn't seem like a worthwhile edge case to add. It should always return an array and since 8.0 *will* always return an array.

### CODE REVIEW

**Comment by othercorey** [comment]
Looks like a few other functions were changed to allow optional arguments, but I have to figure out when they changed since it's not documented.

**Comment by AndrolGenhald** [comment]
> but I have to figure out when they changed since it's not documented.

You can go ahead an open an issue for https://github.com/php/doc-en for that.

**Comment by othercorey** [comment]
> You can go ahead an open an issue for https://github.com/php/doc-en for that.

I submitted patches for missing documentation.

Looks like array_replace $replacements was always optional so that should be the last fix.

**Comment by orklah** [comment]
Thanks for your work on that! That's great!

**Pull request merged**
