### PR TITLE
Improve Reflection stubs

### PR DESCRIPTION
**Pull request by vudaltsov**
ReflectionParameter::getPosition(): non-negative-int
ReflectionProperty non-empty-string $name
ReflectionMethod non-empty-string $name

### CODE REVIEW

**Comment by vudaltsov** [comment]
Okay, but this is such a rear case that it's easier to not take it into account.

**Comment by orklah** [comment]
This has impacts for libraries that need to inherit those class, for example BetterReflection so it would be better to let it that way

**Comment by jorgsowa** [comment]
Could you limit scope to `ReflectionParameter::getPosition`? Then I think it would be useful to merge it.

**Comment by vudaltsov** [comment]
Removed `ReflectionProperty` change. And added another two:
1. ReflectionAttribute::getTarget() returns Attribute::TARGET_* instead of int-mask. Even for attributes of promoted properties (https://3v4l.org/rpM1t).
2. *::getAttributes() always returns a list (https://3v4l.org/LYAMb).

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
