### PR TITLE
[wip] Build phar

### PR DESCRIPTION
**Pull request by weirdan**
This PR adds necessary changes to be able to build Psalm as .phar.
Resulting binary is ~1.6MB~ ~700KB (as opposed to ~28MB~ 23MB "production" (no-dev) composer install).
Build script is provided in `bin/build-phar.sh`.

I considered adding `humbug/box` as a dev dependency, but if I did this I would need to filter out it (and it's dependencies, and psalm's other dev dependencies) when building the phar, so instead I opted for global composer install and producing phar from "production" build.

Some of the `realpath()` calls were dropped because `realpath()` returns `false` on any (even existing) path inside the phar archive.

~Notably the phar version reports issues (possibly false positives, I haven't checked) that regular version does not.~ (not anymore).

### CODE REVIEW

**Comment by muglug** [comment]
This is very great.

I'd like to wait until https://github.com/vimeo/psalm/pull/350 is done (and it seems *so* close), because that'll cut almost 5MB of PHP from the phar.

**Comment by weirdan** [comment]
Don't merge yet, it's broken (see https://github.com/humbug/box/issues/84)

**Comment by weirdan** [comment]
Resolved now.

**Comment by muglug** [comment]
Could you add `file_exists` checks where before `realpath` would return `false`? Then I think this is good to merge.

**Comment by weirdan** [comment]
@muglug done in `src/Psalm/Config.php`. `src/command_functions.php` already had `file_exists()` checks, so I just dropped additional variables that has become excessive with no `realpath()` calls.

**Comment by muglug** [comment]
@weirdan thanks – could you rebase master to clear up merge conflicts? I fear I may have slightly trampled on this unnecessarily.

**Comment by weirdan** [comment]
@muglug sure, done. Interestingly enough, github said there were no conflicts with the base branch.

**Comment by muglug** [comment]
Thanks a lot!

**Comment by mindplay-dk** [comment]
Is there any way to install the `phar` to the `bin` folder in a project?

Global installation doesn't work for me - I want an exact, repeatable dependency installation, so that individual developers (and the CI server) get the same version, and can run it via a Composer script.

And I want the binary phar installation only - I don't want the dependencies of psalm to potentially conflict with the dependencies of the project itself.

I'd also like to be able to package the exact version dependency and all settings as a package - so that we can create and maintain our developer standards and reuse them on many projects.

Any of you have a setup like that on any project for reference?

Thanks :-)

**Comment by weirdan** [comment]
Overall, I'm not aware of a solution that would fit all of your requirements.

> Is there any way to install the phar to the bin folder in a project?

`wget https://github.com/vimeo/psalm/releases/download/3.2.2/psalm.phar` + `git add` + `git commit`. You would have to update it manually from time to time though.

> I don't want the dependencies of psalm to potentially conflict with the dependencies of the project itself.

Psalm itself uses [`bamarni/composer-bin-plugin`](https://github.com/bamarni/composer-bin-plugin), which allows you to have isolated vendor environments. It uses (environment-local) composer install though, not phar.

**Comment by muglug** [comment]
PHPStan has a script that exports the phar to a separate repo: https://github.com/phpstan/phpstan/blob/96c57c66ea24a75a17ec5dff8c684439ac52ead5/.travis.yml#L44-L56

I'll do something similar

**Comment by muglug** [comment]
@mindplay-dk behold:

```
composer require --dev psalm/shim
```

**Comment by muglug** [comment]
This is the change that _should_ add this on every build, and create a comparable tag for every release:

https://github.com/vimeo/psalm/commit/07768cf505b8dcf2d98b2f0c7f44cecfb170e5f5

Maybe `psalm/shim` should be `psalm/phar`? Not sure about that.

**Comment by mindplay-dk** [comment]
Neat! Thanks :-)

Yeah, "shim" seems to imply a filler or placeholder, something that isn't the real thing?

`psalm/phar` or maybe `psalm/bin` would seem fitting :-)

**Comment by muglug** [comment]
I've changed the name everywhere to [`psalm/phar`](https://github.com/psalm/phar)

**Comment by mindplay-dk** [comment]
@muglug is there any way to launch the language-server from the phar?

**Comment by muglug** [comment]
Yes, but only in the latest `master` Phar (from https://github.com/psalm/phar)

Use `--language-server` plus any additional args

**Comment by mindplay-dk** [comment]
Damn, you're on point, man 😃

I got a warning the first time I launched it though (but not the second) - might be a bug?

```
PHP Warning:  file_put_contents(/tmp/psalm/595983f3e8518df3464c6162d2502437041ebc1d-s/config): failed to open stream: No such file or directory in phar:///mnt/c/workspace/kodus-score/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Provider/FileReferenceCacheProvider.php on line 254
```

**Comment by mindplay-dk** [comment]
No luck though, because [this](https://github.com/gtache/intellij-lsp/issues/88).

**Comment by muglug** [comment]
Have you tried running Psalm directly on Windows?

**Comment by mindplay-dk** [comment]
> Have you tried running Psalm directly on Windows?

No. (I don't want to maintain a Windows PHP environment - not since WSL, which lets me run the supported Linux builds of every extension etc... Windows support for PHP extensions is notoriously bad.)

**Comment by muglug** [comment]
Oh interesting!

**Pull request merged**
