### PR TITLE
Applied ArraySpreadInsteadOfArrayMergeRector

### PR DESCRIPTION
**Pull request by weirdan**
Blocked by #7296

### CODE REVIEW

**Comment by orklah** [comment]
Oh, I didn't jnow that one.

Do we know if there's performance considerations here?

**Comment by weirdan** [comment]
From my testing, it seems the function call is slightly slower.

I ran `tests/Internal/CallMapTest.php` 10 times on `master` and this branch:

```console
$ time php-noxdebug vendor/bin/phpunit --repeat=10 tests/Internal/CallMapTest.php
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.1-dev
Configuration: /home/weirdan/src/psalm/psalm/phpunit.xml
Random Seed:   1641442685

...............................................................  63 / 150 ( 42%)
............................................................... 126 / 150 ( 84%)
........................                                        150 / 150 (100%)

Time: 03:05.184, Memory: 72.00 MB

OK (150 tests, 1575360 assertions)
user=185.23s system=0.13s cpu=99% total=3:05.38

$ git co rector-ArraySpreadInsteadOfArrayMergeRector
M	composer.json
Switched to branch 'rector-ArraySpreadInsteadOfArrayMergeRector'

$ php-noxdebug vendor/bin/phpunit --repeat=10 tests/Internal/CallMapTest.php
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.1-dev
Configuration: /home/weirdan/src/psalm/psalm/phpunit.xml
Random Seed:   1641442981

...............................................................  63 / 150 ( 42%)
............................................................... 126 / 150 ( 84%)
........................                                        150 / 150 (100%)

Time: 03:01.241, Memory: 70.00 MB

OK (150 tests, 1575360 assertions)
user=181.31s system=0.12s cpu=99% total=3:01.45
```

The difference seems to be ~3% in this case, but I can't say how representative is that.

**Comment by orklah** [comment]
It's at least an indication of non-worsening so that's fine by me :)

**Review by orklah — APPROVED** [review]

**Comment by orklah** [comment]
@weirdan this should not be blocked anymore if you have time to rebase it

**Comment by weirdan** [comment]
Superseded by #8345

**Pull request closed without merging**
