### PR TITLE
Add missing ldap_unbind mapping for php 8.1

### PR DESCRIPTION
**Pull request by othercorey**
https://www.php.net/manual/en/function.ldap-unbind.php

Seems this function was missed.

### CODE REVIEW

**Comment by orklah** [comment]
Callmap.php should be updated too

**Comment by othercorey** [comment]
All of the ldap_functions in callmap.php seem to use the old `resource` type. How does this work with different php versions?

**Comment by orklah** [comment]
Please take a look at https://psalm.dev/docs/contributing/editing_callmaps/ for the full explanation. Short version: callmap.php contains current signature and versionned files alters it for each successive older version to match with the user's version

**Comment by orklah** [comment]
Thanks! Follow up is welcome :) 

Some contributor recently made a tool to detect inconsistencies in callmaps (through reflection) and flagged ldap_ functions as potentially wrong: https://github.com/vimeo/psalm/pull/8104/files#diff-b16377a21d55a13a48cbdbdfbdf7479b2d9dda80f93b3b81202f88bd1e230b13R97
Your fix was probably the reason that justified excluding this range of functions

You could try to remove this line in a new PR an look at CI results for failures in order to identify cases that would need fixing

**Comment by SamMousa** [comment]
See #8121

**Pull request merged**
