### PR TITLE
Detect redundant identity with true

### PR DESCRIPTION
**Pull request by greg0ire**
Using `=== true` on a known boolean results in the same boolean.

### CODE REVIEW

**Comment by greg0ire** [comment]
The builds seem to be badly broken… looks like there is PHP 8-specific syntax somewhere…

**Comment by weirdan** [comment]
> The builds seem to be badly broken… looks like there is PHP 8-specific syntax in phpunit:

Actually it's an old syntax (`class Match ...`) that's no longer valid for PHP 8 (due to the `match` keyword introduced).
I suspect `nikic/php-parser` needs to be pinned to the version that does not support PHP 8 syntax.

**Comment by weirdan** [comment]
https://github.com/nikic/PHP-Parser/releases/tag/v4.7.0 - I think this is the culprit.

**Comment by weirdan** [comment]
Already reported upstream: https://github.com/nikic/PHP-Parser/issues/690

**Comment by muglug** [comment]
In the meantime, thanks @greg0ire!

**Pull request merged**
