### PR TITLE
Bugfix/splfileobject fputcsv invalidnamedargument

### LINKED ISSUE #8039: InvalidNamedArgument
psalm: InvalidNamedArgument: Parameter $separator does not exist on function SplFileObject::fputcsv

image

### PR DESCRIPTION
**Pull request by KevinVanSonsbeek**
Fixes #8039 

It seems that during the transition from php 7.4  to php 8.0 in some cases param names have changed. I can't find these changes documented on the php wiki (probably due to them not being BC breaking prior to 8.0).

This might however mean that this problem could occur in more places when using named arguments. But finding those changes is most likely a long and tedious (manual?) task, so i suggest fixing them when they pop up.

### CODE REVIEW

**Comment by KevinVanSonsbeek** [comment]
From the php-src repo:
PHP 7.4 branch: [spl_directory.c](https://github.com/php/php-src/blob/fbee73df14a661c3c50703b031c59721194f35e7/ext/spl/spl_directory.c#L3043)
```C
ZEND_BEGIN_ARG_INFO_EX(arginfo_file_object_fgetcsv, 0, 0, 0)
	ZEND_ARG_INFO(0, delimiter)
	ZEND_ARG_INFO(0, enclosure)
	ZEND_ARG_INFO(0, escape)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_file_object_fputcsv, 0, 0, 1)
	ZEND_ARG_INFO(0, fields)
	ZEND_ARG_INFO(0, delimiter)
	ZEND_ARG_INFO(0, enclosure)
	ZEND_ARG_INFO(0, escape)
ZEND_END_ARG_INFO()
```

PHP 8.0 branch: [spl_directory_arginfo.h](https://github.com/php/php-src/blob/3a8912fb7c97ea5a8490037d45224230be10625d/ext/spl/spl_directory_arginfo.h#L173)
```C
ZEND_BEGIN_ARG_INFO_EX(arginfo_class_SplFileObject_fgetcsv, 0, 0, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, separator, IS_STRING, 0, "\",\"")
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, enclosure, IS_STRING, 0, "\"\\\"\"")
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, escape, IS_STRING, 0, "\"\\\\\"")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_SplFileObject_fputcsv, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, fields, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, separator, IS_STRING, 0, "\",\"")
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, enclosure, IS_STRING, 0, "\"\\\"\"")
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, escape, IS_STRING, 0, "\"\\\\\"")
ZEND_END_ARG_INFO()
```

**Comment by AndrolGenhald** [comment]
> I can't find these changes documented on the php wiki (probably due to them not being BC breaking prior to 8.0).
> This might however mean that this problem could occur in more places when using named arguments.

Yep, there've been a lot of fixing for these types of issues already. I bet there are still some that haven't been found yet too.

**Comment by orklah** [comment]
Callmap 80 don't seem to match with callmap_historical.

But if the only change is the parameter name, feel free to change the history too (parameter name were not important before PHP 8.0 so we usually change them retroactively)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
