### PR TITLE
Psalm v6: strict_types=1

### PR DESCRIPTION
**Pull request by danog**
Enables strict types and converts all typehints to native typehints.

### CODE REVIEW

**Comment by weirdan** [comment]
BCC failures need to go to `UPGRADING.md`

**Comment by danog** [comment]
I've added BCC notes for the amp breaking changes, the rest is all stuff that would have been detected by Psalm anyway, so just added a single line for that.

**Comment by danog** [comment]
Should be good to merge @orklah @weirdan! :)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
