### PR TITLE
Remove MixedInferredReturnType

### LINKED ISSUE #9751: MixedInferredReturnType vs MixedReturnStatement
The examples in .md for both are pretty much identical
And they always occur together.

https://psalm.dev/r/6ea0c210bb

`MixedInferredReturnType` seems redundant to me, since it's already reported by `MixedReturnStatement` (which is better, as it reports every return statement)

### PR DESCRIPTION
**Pull request by robchett**
… reported by MixedReturnStatement
fixes #9751

### CODE REVIEW

**Comment by orklah** [comment]
Nice! This will need to be included in Psalm 6 as we can't merge that right now.

@weirdan can you create a milestone?

**Comment by weirdan** [comment]
Sure. I believe you could do this too:

image

**Comment by orklah** [comment]
oh yeah I can, I thought is has a specific interface to create those, thanks!

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
