### PR TITLE
adding php & extension version info to baseline file

### PR DESCRIPTION
**Pull request by SignpostMarv**
as discussed in [twitter thread](https://twitter.com/SignpostMarv/status/1140360049577091073?s=20); 

not sure how to make the info dumping conditional?

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by SignpostMarv** [comment]
you're welcome :)

**Comment by ADmad** [comment]
Is it possible to disable this feature? Working on an OSS project where each contributor may have slightly different patch versions of php/extension this feature causing unnecessary diffs each time someone updates baseline file.

**Comment by muglug** [comment]
I agree it makes it noisy - I've made this opt-in with 73b1571

**Comment by SignpostMarv** [comment]
is there an attribute equivalent to the execution flag ?

**Comment by muglug** [comment]
No, but feel free to create one!

**Pull request merged**
