### PR TITLE
Fully qualify constants and function calls

### PR DESCRIPTION
**Pull request by LeSuisse**
This should give a small performance boost.
Part of #1837.

The change is enforced via phpcs and can be autofixed with phpcbf.

### CODE REVIEW

**Comment by muglug** [comment]
Thanks - this is awesome.

**Comment by iluuu1994** [comment]
Do you think this is measurable? A benchmark would be interesting. Psalm is largely CPU-bound but I still doubt this makes a whole lot of a difference. Maybe I'm wrong.

**Comment by muglug** [comment]
@TysonAndre said it’s about a 3% speed up, and I’ve seen similar figures quoted elsewhere.

**Comment by LeSuisse** [comment]
I did not benchmark the change on Psalm itself but you can find some benchmarks here:
 * https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
 * https://github.com/Roave/FunctionFQNReplacer#benchmark

Even without the perfs improvement this is IMO an interesting change (especially since it can be automated). It removes the temptation of doing ugly things for test purposes like redefining global function in the namespace scope to change the behavior.

**Comment by iluuu1994** [comment]
Fair enough 🙂

**Pull request merged**
