### PR TITLE
Improve array_unique callmap stubs

### PR DESCRIPTION
**Pull request by mathroc**
see #7956

### CODE REVIEW

**Comment by mathroc** [comment]
thank you, I finally got some time to fix it, looks like it needs a label to be fully green but I can't do that

**Comment by orklah** [comment]
Could you drop `associative-array` and just keep `array`?

It seems to be a weird old type that is only in callmap and it doesn't seem to expect `<>` after it so it may not work as expected

**Comment by mathroc** [comment]
> Could you drop `associative-array` and just keep `array`?
> 
> It seems to be a weird old type that is only in callmap and it doesn't seem to expect `<>` after it so it may not work as expected

done, should I have keep it for the `0` flag? (as it doesn't have type parameters)

**Comment by orklah** [comment]
It seem to be exactly handled the same as `array`, except for special handling in `array` so you can keep it like that. I think it's a type that existed at one point in Phan to denote `array<string, ...>` but it doesn't even have this meaning in Psalm

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
