### PR TITLE
fix false positives for partially invalid phpdoc

### PR DESCRIPTION
**Pull request by kkmuffme**
Fix 2 cases specified in https://github.com/vimeo/psalm/issues/7902

Can someone please help me fix the tests, since I don't know how to mock the CodeLocation in FunctionLikeDocblockParserTest.php?

### CODE REVIEW

**Comment by orklah** [comment]
if you make the test extends Psalm\Tests\TestCase, you should be able to do basically this: https://github.com/vimeo/psalm/blob/20351c6667e4f4e2443ea9aca6d5cde610aaaf8d/tests/TestCase.php#L140. FileAnalyzer can be given to CodeLocation and only needs a ProjectAnalyzer that you can retrieve on the properties

**Comment by kkmuffme** [comment]
@orklah sorry, could you pinpoint me on how to proceed? I updated everything for the test cases, however I still don't get how to get the CodeLocation (see my @todo comment in the last commit)

**Comment by orklah** [comment]
just go with new CodeLocation and give it what it asks for. One of those thing is a FileAnalyzer that you can retrieve like I explained earlier

**Comment by kkmuffme** [comment]
That is the exact question. CodeLocation wants:

```
FileSource $file_source,
PhpParser\Node $stmt,
```

I have nothing of that sort available in those tests, since I only have a php docblock string.
How would `new FileAnalyzer( ` help? I don't have a file either, just this php docblock string.

**Comment by orklah** [comment]
FileAnalyzer is a FileSource so you can give it to CodeLocation.

For the Node, you can do a new String_('randomString');, it should work

**Comment by kkmuffme** [comment]
@orklah all mocked now except `PhpParser\Node`, which causes the tests to fail. Please advise on how to mock this here, so tests pass.

**Comment by orklah** [comment]
you can do a `new String_('randomString');`, it should work

**Comment by kkmuffme** [comment]
@orklah But it doesn't :-) I tried all variations of that and none worked unfortunately.

**Comment by orklah** [comment]
String_ must obviously be a child of Node, so it's in PHPParser, not in global namespace: PhpParser\Node\Scalar\String_

Don't you have an IDE to help you with that?

**Comment by kkmuffme** [comment]
I'm devops not a PHP developer and I don't have this setup on my local computer. Working on SSH terminal. That's why I cannot run tests but always have to use the Github pipeline to test the tests.

Anyway, all tests pass now. It's ready to be merged :-)

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
