### PR TITLE
Respect stubs in all cases

### PR DESCRIPTION
**Pull request by mmcev106**
If stubs should NOT be respected in all cases, I can modify this to only change behavior in the specific test case. Don't hesitate to ask if you have any questions, or would prefer this be implemented in a different way.

### CODE REVIEW

**Comment by mmcev106** [comment]
I'm working on fixing the code style now.

**Comment by orklah** [comment]
test-with-real-projects is broken for another reason, don't worry about it ;)

**Comment by mmcev106** [comment]
Thanks @orklah.  The code style has been fixed.

**Comment by orklah** [comment]
I'm afraid of possible side effects from this. Could you target master instead so it will release with Psalm 6? it will be easier to manage if there are issues

**Comment by mmcev106** [comment]
@orklah, I've changed the base branch to `master`, and added an empty commit to force tests to re-run.  Let me know if anything else is needed.

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
