### PR TITLE
Implement by-ref closure use analysis

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by danog** [comment]
@orklah/@weirdan updating the baseline on https://github.com/psalm/endtoend-test-psl should fix, but I don't have push access, could someone do that after merging?

**Comment by orklah** [comment]
I don't have write permissions either. Should I still merge this?

**Comment by danog** [comment]
Yeah @orklah let's merge this, let's just tag @weirdan once more so he gives us both push permissions when he finds some time :)

**Comment by danog** [comment]
Thanks @weirdan, no problem!)

@orklah can you merge this now that tests are passing? :)

Also, could you also tag a release after merging https://github.com/vimeo/psalm/pull/10439 and https://github.com/vimeo/psalm/pull/10431 as well? I believe the feature present in this PR would be very much appreciated :)

**Comment by danog** [comment]
@orklah Done!

**Pull request merged**
