### PR TITLE
Fix issues in php 8.0 delta

### PR DESCRIPTION
**Pull request by TysonAndre**
In a last minute change in php 8.0 after the feature freeze,
PhpToken::getAll was changed to tokenize

Also, https://www.php.net/manual/en/function.mb-get-info
has been around since php 4.2 - it's in psalm/dictionaries/CallMap.php
already with the same signature. Same for ReflectionNamedType::isBuiltin

Also, add signatures for getAttributes.

Also, use the same param names for fdiv that are found in reflection in
php 8.0 and 8.1 to support named arguments

### CODE REVIEW

**Comment by weirdan** [comment]
I'm going to fix issues in this PR.

**Comment by TysonAndre** [comment]
Oh, CallMap.php is using 8.0 as the base. And mb_get_info should be in CallMap_historical.php. I'd assumed that psalm was still using 7.x as a base

> I'm going to fix issues in this PR.

Will let you do that since you've already started

**Comment by weirdan** [comment]
Yeah, 'historical' is for 7.0 and below, while `CallMap.php` is targeting current version (8.0).

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
