### PR TITLE
Using psalm in non class context (fixes #4162)

### LINKED ISSUE #4162: Using psalm in phtml files
I'm trying to make psalm work on `.phtml` files.
Everything goes well, except for one thing. All classes (which should be autoloaded) are undefined. In normal php classes they get loaded by psalm.

Following throws `UndefinedDocblockClass` for `CustomBlocks`.

    //my-template.phtml
    
    <?php 
    use MyNamespace\Block\CustomBlocks

    /** @var CustomBlocks $block */
    ?>

### PR DESCRIPTION
**Pull request by quisse**
Here's my attempt to solve #4162. Not sure where/how to test this. Some guidance would be appreciated. 🙏

### CODE REVIEW

**Comment by muglug** [comment]
This block should be entered, doing the same thing – why isn't it?

https://github.com/vimeo/psalm/pull/4512/files#diff-ae2c8476b4a0a9a9ee93e6d04d483a0b14f967e8dd7c6a3251d9e2338e865170L348

**Comment by quisse** [comment]
I'm not sure what you mean. The link you've provided only shows the files changed of this PR.

**Comment by quisse** [comment]
Discussed: https://github.com/vimeo/psalm/blob/8ede667cadff38d9e6bfb554bfa91a00cc18e721/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php#L365 should make it work. I should check why it doesn't.

**Comment by quisse** [comment]
Hmmm, it seems like f3cc7a7f2fb9611abe5db5462d7d0ff8d3d9d164 has solved the issue already.

**Pull request closed without merging**
