### PR TITLE
Add more impure functions to configuration

### LINKED ISSUE #2050: Call to session_name is unused
```php
session_name('SVSESSID');
@session_start();
```

> UnusedFunctionCall - 3:1 - The call to session_name is not used

https://psalm.dev/r/a71f956ab5

This shouldn't error.

**EDIT**: 

Same thing with:

*  `session_id`
* `ldap_set_option`

### PR DESCRIPTION
**Pull request by iluuu1994**
Closes #2050

### CODE REVIEW

**Comment by iluuu1994** [comment]
This list is very incomplete, it's just the ones I found in our codebase.

**Comment by iluuu1994** [comment]
`session_id` and similar functions that act as getters and setters are unfortunate. If you call `session_id()` without parameters that will be a false negative after this PR...

**Comment by muglug** [comment]
> If you call session_id() without parameters that will be a false negative after this PR

I can live with that! Thanks!

**Comment by iluuu1994** [comment]
Thanks @muglug 🙂

**Pull request merged**
