### PR TITLE
Remove (and prevent) unused uses

### PR DESCRIPTION
**Pull request by weirdan**
* Updates `slevomat/coding-standard`
* Removes unused uses
* Prevents unused uses
* Fixes a number of symbol case mismatches

### CODE REVIEW

**Comment by weirdan** [comment]
The failing test is interesting. It fails locally for all commits since https://github.com/vimeo/psalm/commit/3e9c5d3600c3d053411593b73e9cb8dd676d1144, identified with `git bisect`, but I didn't see it failing neither locally nor in CI before this PR.

**Comment by muglug** [comment]
new PHP Parser version just dropped: https://github.com/nikic/PHP-Parser/releases/tag/v4.10.5

Hold please

**Comment by weirdan** [comment]
Ah, that explains it.

**Comment by muglug** [comment]
Merge/rebase master and you should be away

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
