### PR TITLE
Merge 5.x

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by orklah** [comment]
Thanks! There were a few failures in CI so I couldn't merge and I merged some PR in the meantime

**Comment by danog** [comment]
@orklah Should be good to merge, slightly tweaked the logic introduced by @issidorov in https://github.com/vimeo/psalm/pull/10385 due to changes in the magic method logic that were made on master by https://github.com/vimeo/psalm/pull/10361, now magic static methods should be returned as well when fetching instance methods (I suppose the order could be tweaked a bit, but it isn't inherently wrong because non-magic static methods are already returned by the current logic).

**Comment by danog** [comment]
Hmm it seems the circleci tests are actually failing due to https://github.com/vimeo/psalm/pull/10361, ping @robchett

**Comment by danog** [comment]
@orklah can we merge this at least to fix the phar build on master

**Comment by danog** [comment]
Submitted https://github.com/php-standard-library/psalm-plugin/pull/15 to fix the PSL issues upstream

**Comment by orklah** [comment]
Thanks!

**Comment by robchett** [comment]
@danog can you point me in the direction of the issue here? I'm not really sure what I'm looking for/at

**Comment by danog** [comment]
@robchett fixed the issue already in https://github.com/vimeo/psalm/pull/10369/commits/2eed29209caebbb9df9e9af1d6f69c3ab33185d1

**Comment by robchett** [comment]
Ah, thank you!

**Pull request merged**
