### PR TITLE
Make md5 return type more precise

### PR DESCRIPTION
**Pull request by fluffycondor**

### CODE REVIEW

**Comment by jack-worman** [comment]
Is it impossible for md5() to return all zeros?

`php -r "var_export((bool) "00000000000000000000000000000000");"`
false

**Comment by orklah** [comment]
Are you sure?
https://3v4l.org/6cLB2

**Comment by jack-worman** [comment]
That is very strange. Why is the inline cli version returning the wrong answer...?
Screenshot 2022-12-18 at 11 22 58 AM

**Comment by orklah** [comment]
I was starting to get really confused at that too :p

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
