### PR TITLE
Add note for 5.1 BC break

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by weirdan** [comment]
Shouldn't we mark `TList` and `TNonEmptyList` as deprecated?

**Comment by danog** [comment]
Ah yes good idea

**Comment by orklah** [comment]
Shouldn't this be included in Psalm 5? Seems like a big BC break for plugins, no?

**Comment by danog** [comment]
Yes but it's a lot of work and my https://github.com/danog/psalm/tree/tnon_empty_list_refactoring branch is not ready yet, and I really don't want to hold back the release any longer for a last-minute idea :P 
I feel like forewarning about an near-future BC break during a major release ought to be enough.

**Comment by danog** [comment]
I've already created Type::getListAtomic and Type::getNonEmptyListAtomic methods in https://github.com/danog/psalm/tree/tnon_empty_list_refactoring and I've already replaced them across the entire codebase, I could copy in a placeholder version in this PR as well.

**Comment by danog** [comment]
All done!

**Pull request closed without merging**
