### PR TITLE
Initial proposal for psalm-require-{extends, implements}

### PR DESCRIPTION
**Pull request by NiclasvanEyk**
This is an attempt to implement the `@psalm-require-extends` and `@psalm-require-implements` annotations, as discussed in #4356. It only concerns the static analysis regarding traits for now, wo the targeted behaviour is as follows:

For `@psalm-require-extends` on traits
```php
<?php
class A {}

/** @psalm-require-extends A */
trait RequiresA {}

class Invalid {
  use RequiresA; // This should throw an error
}

class Valid extends A {
  use RequiresA; // This is valid, as A is extended
}
```

For `@psalm-require-implements` on traits
```php
<?php
interface A {}
interface B {}

/** 
 * @psalm-require-implements A 
 * @psalm-require-implements B
 */
trait RequiresAB {}

class Invalid {
  use RequiresAB; // This should throw an error
}

class AlsoInvalid implements A {
  use RequiresAB; // This should throw an error
}

class Valid implements A, B {
  use RequiresAB; // This is valid, as A *and* B are implemented
}
```

### CODE REVIEW

**Comment by muglug** [comment]
Great start!

You're missing an entry in `config.xsd` for `ExtensionRequirementViolation` and also documentation for the issue – the markdown file you create for documentation will need a snippet of PHP that demonstrates the issue (you can copy-paste the code from a test).

**Comment by NiclasvanEyk** [comment]
Thank you for the quick feedback, I will implement it!

What is the recommended approach for filling the `SHORTCODE` and `ERROR_LEVEL` constants on a subclass of `CodeIssue`?

**Comment by weirdan** [comment]
For `SHORTCODE` I'd suggest running `php bin/max_used_shortcode.php` and taking the next available value.

**Comment by muglug** [comment]
`ERROR_LEVEL` should be `-1` — that makes it always trigger, which is what we want for any user-opted-in situations (where Psalm-specific annotations the user has added trigger issues)

**Comment by NiclasvanEyk** [comment]
Ok, I added docs, entries in `config.xsd` and shortcodes taken from `bin/max_used_shortcode.php`. If there is still something missing, just let me know.

As this is now enough to impose both types of restriction and have them be checked by psalm I'll clear the draft status. The CI fails, but the issues seem to be unrelated to the added code, so I am not sure how to proceed here.

I would also want to add some code, so the language server would provide methods from the requirements like this:
```php
class A {
  public function foo() {}
}

/** @psalm-require-extends A */
trait B {
  public function bar()
  {
    $this-> // LS/IDE would suggest foo, because of the require-extends annotation
  }
}
```

but I feel this is better implemented in a following pr.

**Comment by muglug** [comment]
Thanks, I'll deal with the remaining issues

**Comment by muglug** [comment]
You accidentally removed a `use` statement here: https://github.com/vimeo/psalm/commit/0261024aa6b2921afb02b3f0c1efb57dd9bd7020#diff-4e427d91e2dcbfd421d5b849eb4e67efbe4885079b87ac618001820dc44fa339L20

**Pull request merged**
