### PR TITLE
feature: universal object crates

### PR DESCRIPTION
**Pull request by mr-feek**
This is a draft for implementing phpstan's concept of "[universal object crates](https://phpstan.org/config-reference#universal-object-crates)". 

What do we think? I have yet to test with an actual config file, but the unit test I added is passing.

### CODE REVIEW

**Comment by weirdan** [comment]
I'd like to also have an annotation for this.

**Comment by muglug** [comment]
Looks great! Rebase to fix the build, sorry

**Comment by mr-feek** [comment]
@weirdan annotation would be cool! A bit out of my grasp though, feel free to follow up with it

**Comment by muglug** [comment]
Sorry this took so long to merge, and thanks again!

**Pull request merged**
