### PR TITLE
Use pretty print for JSON reporting.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/vimeo/psalm/issues/3360

Any preference on the implementation? Or is it OK as such?
I only modified the reporting (not internal JSON encoding for hashing etc), and I put the constants into a dedicated class to keep it DRY and easy to maintain.
While doing that I also captured the "theoretical" `false` return to make the return result more "true" towards documented and expected type `string`.

The constants are used as such for a lot of libraries and frameworks as such, e.g.
psalm/vendor/phpunit/phpunit/src/Util/Json.php

### CODE REVIEW

**Comment by muglug** [comment]
Actually is there a reason you can't have a separate `json-pretty` output format? It's possible that some won't expect the json-encoded output to have newlines (as `json_encode` by default converts any in strings to the `"\n"` character), so seeing a pretty-printed output might break stuff.

**Comment by dereuromark** [comment]
Yes, there could also be some flag/option for this on top, of course.

**Comment by dereuromark** [comment]
The psalm errors seem to be a deficiency of psalm itself, right?

**Comment by muglug** [comment]
> The psalm errors seem to be a deficiency of psalm itself, right?

Sort of. There's no _great_ way to resolve constants referenced with `static::`, as they could be overridden downstream.

One way is to take the docblock type (and also verify a constant's docblock type against the calculated one) but that tends to be a pretty edge case. I think there's an issue somewhere.

**Comment by dereuromark** [comment]
Code wise static:: is always more correct than self:: as it allows the extension (which in library code should always be the case). No need to protect developers from themselves beyond basic due diligence. Yes, it can and should be able to be overwritten on project level, as long as one sets the same type of course.
But that's a topic for a different discussion :) So fair enough then.

**Comment by muglug** [comment]
> Code wise static:: is always more correct than self::

I very much disagree there – PHP doesn't allow you to set constants `final`, but that seems to be a design flaw more than anything else. For example, I never want `self::DAYS_IN_WEEK` to change.

**Comment by muglug** [comment]
Thanks!

**Comment by dereuromark** [comment]
Yes, those are "final" constants, here you could use self indeed.
But other cases could be very well extendable, thus psalm shouldn't error in those IMO.

**Pull request merged**
