### PR TITLE
Speed up Windows tests

### PR DESCRIPTION
**Pull request by weirdan**
Enable multiple workers for Windows, just like we do on Linux already.

### CODE REVIEW

**Comment by orklah** [comment]
That's cool!

**Comment by bendavies** [comment]
very nice. I wondered why I didn't do windows when i originally did #4985.
turns out the tests weren't ran on windows at the time.

**Comment by orklah** [comment]
> turns out the tests weren't ran on windows at the time.

They were, but they ran in AppVeyor until https://github.com/vimeo/psalm/pull/6173. I migrated them on GA but I didn't look up how to translate the splitting script on windows

**Comment by bendavies** [comment]
Ah right you are

**Pull request merged**
