### PR TITLE
Use getSingleAtomic() instead of array_values(getAtomicTypes())[0].

### PR DESCRIPTION
**Pull request by AndrolGenhald**

### CODE REVIEW

**Comment by orklah** [comment]
Oh, nice. I think we also have some reset() and array_pop/array_unshift that does that too

**Comment by AndrolGenhald** [comment]
> Oh, nice. I think we also have some reset() and array_pop/array_unshift that does that too

I don't think so. If there are any they have to be assigned to a variable first since those take the argument by reference, so it's a lot harder to find.

**Comment by orklah** [comment]
Well, I usually use regex for that kind of searches.
Try things like
`array_shift\(\$.+type`
`array_pop\(\$.+type`
`reset\(\$.+type`

There's quite a few :)

But no worries if you don't want to do those, we'll do that later

**Comment by AndrolGenhald** [comment]
Actually there is one, I'll fix it in a minute.

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
