### PR TITLE
Fix remaining ignored CallMap return types that can be updated

### PR DESCRIPTION
**Pull request by othercorey**
The remaining functions are either ignored on purpose, have incorrect types in PHP or are just hard to figure out and therefore not sure if should be changed.

### CODE REVIEW

**Comment by orklah** [comment]
Seems like a inconsistency is still there according to CI, but it looks great!

**Comment by othercorey** [comment]
> Seems like a inconsistency is still there according to CI, but it looks great!
 
Re-added the xmlrpc functions for this PR. We can drop this entire set of functions for php 8.0 since the extension was unbundled and is abandoned.

**Comment by orklah** [comment]
good to know! A new failure appeared in the meantime :p

**Comment by othercorey** [comment]
> good to know! A new failure appeared in the meantime :p

Should be good. I only run certain checks locally when doing these.

**Comment by orklah** [comment]
Thanks a lot!

**Pull request merged**
