### PR TITLE
Analyze attribute statements instead of constructing virtual statements.

### LINKED ISSUE #7685: Psalm could not infer this type being passed inside the php8 attribute
Psalm version: 4.20.0
Php version: 8.1

Error ouptput:
```
ERROR: InvalidArgument - app/Requests/UpdateUserRequest.php:43:17 - Argument 7 of OpenApi\Attributes\Patch::__construct expects array<array-key, OpenApi\Attributes\Parameter>|null, array{"Psalm could not infer this type"} provided (see https://psalm.dev/004)
    parameters: [
        new Parameter(name: 'id', description: 'User ID', in: 'path', required: true),
 ],
```

### PR DESCRIPTION
**Pull request by AndrolGenhald**
Fixes #7685.

My main worry here is that the code locations might get messed up somehow. I added the line/column numbers to the existing tests, but is there a way to test the ending column of the message in addition to the starting column?

### CODE REVIEW

**Comment by orklah** [comment]
I never tried to check issue location like that.

It seems fine to me

**Comment by AndrolGenhald** [comment]
Looks ready to me, I'll double check on psalm.dev after it's merged to make sure locations are correct.

**Comment by orklah** [comment]
Thanks!

**Comment by weirdan** [comment]
>  I'll double check on psalm.dev after it's merged 

Merged to master, should be available on psalm.dev shortly.

**Pull request merged**
