### PR TITLE
Docs/template types

### PR DESCRIPTION
**Pull request by SignpostMarv**
PRing the change I want to see in the world :D

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by SignpostMarv** [comment]
yw :D

any thoughts on https://github.com/vimeo/psalm/pull/1285#commitcomment-32202766 ?

**Comment by muglug** [comment]
> any thoughts on [#1285 (comment)](https://github.com/vimeo/psalm/pull/1285#commitcomment-32202766) ?

Definitely a bug

**Comment by SignpostMarv** [comment]
shall I file that separately ?

**Comment by muglug** [comment]
Yes please!

> [I originally had this set up as a ternary inside `Foo::getIterator()`](https://getpsalm.org/r/b86abe0fbc), but it seems psalm doesn't identify the conditional types yielded/returned.

Yeah, Psalm wasn't telling you that it was an error, but it is - fixed in https://github.com/vimeo/psalm/commit/899dd16e8f804e420c94e9136921cf34ac96ba7c

**Comment by SignpostMarv** [comment]
filed under #1288

**Pull request merged**
