### PR TITLE
Contextual inference for closure param types

### LINKED ISSUE #5820: closure parameter are analysed without the function context ( generics ) when used with userland functions.
The following example shows the issue: https://psalm.dev/r/3e6b2451c3

both map and array_map act the same way, however, psalm complains about missing `@param` type declaration for the closure with user land implementations, but not builtin array_map. 

This results in useless type declaration being added ( see https://psalm.dev/r/15e391e947 ) to satisfy psalm.

### LINKED ISSUE #7209: Contextual inference for Closure param types
It's very painful that psalm can't infer closure parameters from context:
https://psalm.dev/r/310e6ed76e

Of course we can specify type hint. But if type have templates it will be lost:
https://psalm.dev/r/b60a08d22a

Doc blocks preserves templates, but code looks bad:
https://psalm.dev/r/7c9621b9d3

We could write code like this:
```php
/** @var list<Foo<int>> */
$fooList = [];
$mapped = map($fooList, fn(Foo $foo) => [$foo]);

// $mapped is list<Foo<array{int}>>. No doc blocks!
```

From what I've learned, it is relatively easy to implement left-to-right args type resolving for furter closure params inference.
I don't think Psalm needs a right-to-left analysis that was be mentioned in #5820. From my point of view its rare and difficult case.

### PR DESCRIPTION
**Pull request by klimick**
Closes #7209

Also solves my problem from #4535
Partially addresses #5820

### CODE REVIEW

**Comment by klimick** [comment]
Appearing `UnnecessaryVarAnnotation` in the psl is reasonably. What should I do in this case?

**Comment by weirdan** [comment]
I'll baseline that error once this PR is merged.

**Review by weirdan — APPROVED** [review]
LGTM.

**Comment by orklah** [comment]
Thanks!

**Review by orklah — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
