### PR TITLE
Work in progress - resolve directories from config file location

### PR DESCRIPTION
**Pull request by bdsl**
As discussed a while back at https://github.com/vimeo/psalm/issues/1524

Build of ef7005f at https://circleci.com/workflow-run/8cadee31-973a-4e66-a724-c82bf0ae2d13

### CODE REVIEW

**Comment by bdsl** [comment]
I'm not sure the tests are now failing on AppVeyor, but passing on Circle and Travis. Maybe to do with running on windows? I don't have a Windows machine myself to try the tests locally. I thought at first it could be the `/` used as directory separator,  but that's been in place for 20 days in `PsalmEndToEndTest`. https://github.com/vimeo/psalm/blame/ef7005f68c0c30f02c44a4cdc91f54c0810b520f/tests/EndToEnd/PsalmEndToEndTest.php#L33

I'd be grateful if anyone else has an idea or wants to try running the tests on WIndows.

**Comment by bdsl** [comment]
I'm not sure the tests are now failing on AppVeyor, but passing on Circle and Travis. Maybe to do with running on windows? I don't have a Windows machine myself to try the tests locally. I thought at first it could be the `/` used as directory separator,  but that's been in place for 20 days in `PsalmEndToEndTest`. https://github.com/vimeo/psalm/blame/ef7005f68c0c30f02c44a4cdc91f54c0810b520f/tests/EndToEnd/PsalmEndToEndTest.php#L33

I'd be grateful if anyone else has an idea or wants to try running the tests on WIndows.

**Comment by muglug** [comment]
> Maybe to do with running on windows?

Yeah, it's the end-to-end tests that are failing - I've just turned AppVeyor integration on

**Comment by muglug** [comment]
anyway, thanks!

**Comment by bdsl** [comment]
Ah ok, I thought it was something in my changes that had broken them. 

Also I'm not sure if this PR was ready to be merged - I made it to make what I'm doing more visible, but I wanted do some more work to make sure all the relevant use cases were working and tested. I think currently `psalm --alter` is broken when config file has `resolveFromConfigFile="true"`, which they will by default:

https://github.com/vimeo/psalm/blob/94f934627c6901e2e85e2cf7dc1384e2af9a0909/tests/EndToEnd/PsalmEndToEndTest.php#L94

And I think the executables other than `psalm`, e.g. `psalter`, `psalm-language-server` etc are not honouring the new setting.

@muglug maybe you want to revert this PR and I should be able to resubmit it today with improvements..

**Comment by muglug** [comment]
I’m not going to create a release until Monday at the earliest, so I think it’s fine to stay as-is. In the future feel free to create a draft PR!

**Comment by bdsl** [comment]
Ok, I will look for the draft PR button next time, since I generally like to keep the master branch of any project ready-to-release at all times.

**Pull request merged**
