### PR TITLE
Report invalid number of arguments for psalm-taint-*

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/vimeo/psalm/issues/7046

I tried testing the change via `TaintTest.php` but was not able to figure out how to properly assert the new error/exception

### CODE REVIEW

**Comment by weirdan** [comment]
And it immediately found broken tag in our tests: https://github.com/vimeo/psalm/blob/ff66d24a4b3411f5313994ec195d0621cc3e7775/tests/Template/ConditionalReturnTypeTest.php#L762

**Comment by staabm** [comment]
thanks for the hint. I was not able to tell where the problem is/was based on the errors within the github actions.

is it expected that the error message does not point to the actual cause of the problem? or is this bad error message related to my changes in this PR?

```
1) Psalm\Tests\Template\ConditionalReturnTypeTest::testValidCode with data set "classConstantDefault" ('<?php\n                    cl...["a"];')
  Psalm\Exception\CodeException: MixedArrayAccess - src/somefile.php:40:26 - Cannot access array value on mixed variable 
  
  /home/runner/work/psalm/psalm/src/Psalm/IssueBuffer.php:327
  /home/runner/work/psalm/psalm/src/Psalm/IssueBuffer.php:148
  /home/runner/work/psalm/psalm/src/Psalm/IssueBuffer.php:158
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php:1062
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php:592
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/ArrayFetchAnalyzer.php:228
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:313
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:88
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/Statements/EchoAnalyzer.php:40
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:557
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php:197
  /home/runner/work/psalm/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php:178
  /home/runner/work/psalm/psalm/tests/TestCase.php:142
  /home/runner/work/psalm/psalm/tests/Traits/ValidCodeAnalysisTestTrait.php:82
  ```

**Comment by weirdan** [comment]
Our tests perform checks against the first emitted error, but when you throw an exception from the parser, two things happen:
1. Entire docblock is ignored (this is what caused the test to fail)
2. The exception is converted to `MissingDocblockType` (misleading), stored and emitted much later. Therefore, the first issue emitted was `MixedArrayAccess`.

A better approach, I suppose, would be adding the issue to IssueBuffer directly, like it's done here:

https://github.com/vimeo/psalm/blob/c3526b44639d2b7561dca010da1e6f4d456658dc/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockParser.php#L125-L130

**Comment by staabm** [comment]
great, after the suggested change we get a better error message:

```
There was 1 error:

1) Psalm\Tests\Template\ConditionalReturnTypeTest::testValidCode with data set "classConstantDefault" ('<?php\n                    cl...["a"];')
Psalm\Exception\CodeException: InvalidDocblock - src\somefile.php:17:25 - @psalm-taint-source expects 1 argument

C:\dvl\Workspace\psalm\src\Psalm\IssueBuffer.php:327
C:\dvl\Workspace\psalm\src\Psalm\IssueBuffer.php:148
C:\dvl\Workspace\psalm\src\Psalm\IssueBuffer.php:158
C:\dvl\Workspace\psalm\src\Psalm\Internal\PhpVisitor\Reflector\FunctionLikeDocblockParser.php:290
C:\dvl\Workspace\psalm\src\Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner.php:446
C:\dvl\Workspace\psalm\src\Psalm\Internal\PhpVisitor\ReflectorVisitor.php:207
C:\dvl\Workspace\psalm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:200
C:\dvl\Workspace\psalm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:114
C:\dvl\Workspace\psalm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:223
C:\dvl\Workspace\psalm\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:91
C:\dvl\Workspace\psalm\src\Psalm\Internal\Scanner\FileScanner.php:79
C:\dvl\Workspace\psalm\src\Psalm\Internal\Codebase\Scanner.php:554
C:\dvl\Workspace\psalm\src\Psalm\Internal\Codebase\Scanner.php:782
C:\dvl\Workspace\psalm\src\Psalm\Internal\Codebase\Scanner.php:428
C:\dvl\Workspace\psalm\src\Psalm\Internal\Codebase\Scanner.php:280
C:\dvl\Workspace\psalm\src\Psalm\Codebase.php:505
C:\dvl\Workspace\psalm\tests\TestCase.php:127
C:\dvl\Workspace\psalm\tests\Traits\ValidCodeAnalysisTestTrait.php:82

ERRORS!
Tests: 37, Assertions: 36, Errors: 1.

```

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
