### PR TITLE
int-return form of version_compare takes only two arguments

### PR DESCRIPTION
**Pull request by SignpostMarv**
re: #1576

### CODE REVIEW

**Comment by SignpostMarv** [comment]
I'm a little wary of 4efdc6b, as I'm not sure why `\x3c` and `\x3e` are in use instead of the literal brackets?

**Comment by SignpostMarv** [comment]
thinking I might need to PR phpunit, as `PHPUnit\Util\Configuration::satisfiesPhpVersion()` is typed for bool, but "===" would result in null. https://3v4l.org/VE3PX

**Comment by muglug** [comment]
@SignpostMarv please PR in `muglug/phpunit`

**Comment by SignpostMarv** [comment]
muglug/phpunit#3

**Comment by muglug** [comment]
Thanks, I added this manually

**Pull request closed without merging**
