### PR TITLE
Update password function types for PHP 7.4

### PR DESCRIPTION
**Pull request by ShiraNai7**
Possible fix for #2395

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by ShiraNai7** [comment]
@muglug 654a792 broke part the fix though. `PASSWORD_DEFAULT` is `null` since PHP 7.4 so `isset()` won't work with it.

https://psalm.dev/r/0e4386d00b

It works in the playground, but not locally with PHP 7.4:

```
ERROR: UndefinedConstant - test.php:3:28 - Const PASSWORD_DEFAULT is not defined
echo \password_hash('123', PASSWORD_DEFAULT


ERROR: MixedArgument - test.php:3:28 - Argument 2 of password_hash cannot be mixed, expecting int|null|string
echo \password_hash('123', PASSWORD_DEFAULT
```

**Comment by muglug** [comment]
OH I'm dim, sorry

**Comment by muglug** [comment]
Fixed now

**Pull request merged**
