### PR TITLE
Prevented crashes on `array_map(...)`

### PR DESCRIPTION
**Pull request by weirdan**
Fixes vimeo/psalm#7305

### CODE REVIEW

**Comment by orklah** [comment]
maybe add a TODO to signal that we're missing something at that place?

**Comment by weirdan** [comment]
Are we?

**Comment by orklah** [comment]
I didn't look in details what the code here does but I'd expect first class callable to be replaced with a callable or something, no?

**Comment by weirdan** [comment]
With this patch applied, we already do the best we can short of supporting generic closures. For `array_map(...)` Psalm infers `pure-Closure(callable|null, array<array-key, mixed>, array<array-key, mixed>...=):array<array-key, mixed>`. I don't see how it could get any better (without generic closures, that is).

**Comment by orklah** [comment]
Nevermind then 🙂 what do you call generic closures?

**Comment by weirdan** [comment]
E.g. this `Closure<T1 of scalar, T2 of object>(T1, T2):T1|T2`

**Comment by tm1000** [comment]
This actually results in a bug:

```Call to undefined method PhpParser\Node\Expr\FuncCall::isFirstClassCallable()```

That method `isFirstClassCallable` does not exist on `PhpParser\Node\Expr\FuncCall`

**Comment by orklah** [comment]
FuncCall extends CallLike which has isFirstClassCallable method. Mind posting the entire stack along with your installed version of PHP-Parser in a new issue?

**Comment by tm1000** [comment]
@orklah see https://github.com/vimeo/psalm/issues/7378

It does not have that call.

**Comment by tm1000** [comment]
@orklah figured it out: see: https://github.com/vimeo/psalm/issues/7378

Thanks for pointing that out! sorry for the distractions!

**Pull request merged**
