### PR TITLE
SimpleXMLIterator is not always truthy

### LINKED ISSUE #6865: SimpleXMLIterator can be falsey
See also #4814 - #6650 needs some expansion

https://3v4l.org/fk96N

https://psalm.dev/r/40e441d4f2

I've also seen this error from calls to `children()`

### PR DESCRIPTION
**Pull request by jnvsor**
Fixes #6865

### CODE REVIEW

**Comment by jnvsor** [comment]
Please note that this is my first PR, heavily based off #6650. I'm not entirely sure what the ReconcilerTest does, so it may need changes. Please review, thanks

**Comment by orklah** [comment]
put it back to draft, I clicked on the wrong button :)

Seems good at first glance

**Comment by jnvsor** [comment]
> Seems good at first glance

Then I'll set it ready for review (I was under the impression that was what draft was for, haven't made a PR on GH in a while)

**Comment by orklah** [comment]
Draft is to signal maintainers you're not ready to merge. Usually for WIP PR.

Thanks! That's great!

**Pull request merged**
