### PR TITLE
Make `$http_response_header` a non-empty-list

### PR DESCRIPTION
**Pull request by fluffycondor**
This list always contains at least one element: http status code. So I think it's safe to assume it's a non-empty-list.
https://www.php.net/manual/en/reserved.variables.httpresponseheader.php

### CODE REVIEW

**Comment by weirdan** [comment]
It's undefined in CLI though:

image

**Comment by fluffycondor** [comment]
> It's undefined in CLI though

Yep. the current inmplementation is quite naive, because $http_response_header exists only after performing a successful network request.
PHPStan assumes it exists only after calling `fopen` or `file_get_contents`: https://github.com/phpstan/phpstan-src/blob/1.9.x/src/Analyser/NodeScopeResolver.php#L1993

**Comment by weirdan** [comment]
It probably makes sense to mark it as possibly undefined, similar to `$_SERVER['argv']`:
```php
            $argv_helper = new Union([
                Type::getNonEmptyListAtomic(Type::getString())
            ], ['possibly_undefined' => true]);
```

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
