### PR TITLE
load an xdebug stub when required, re: vimeo/psalm#2118

### PR DESCRIPTION
**Pull request by SignpostMarv**
couldn't quite figure out how to load the extension conditionally, variable seems to get lost after restart.

### CODE REVIEW

**Comment by SignpostMarv** [comment]
> To see if the process was restarted you could use one of `XdebugHelper` methods, e.g. [`getSkippedVersion()`](https://github.com/composer/xdebug-handler#getskippedversion).

@weirdan I didn't catch that last night- guessing that check would go here? https://github.com/vimeo/psalm/blob/849d1e1574b18162d98a4de0a05cec1d592e776f/src/psalm.php#L317

My initial plan was to make `Config::$load_xdebug_stub` a nullable bool, allowing the end-user to prevent the stub from being loaded by specifying `loadXdebugStub="false"`.

i.e.
```php
if (is_null($config->load_xdebug_stub) && '' !== $ini_handler->getSkippedVersion()) {
    $config->load_xdebug_stub = true;
}
```

**Comment by SignpostMarv** [comment]
@weirdan got that sorted in 5613688, ta :)

**Comment by muglug** [comment]
Thanks!

**Comment by SignpostMarv** [comment]
you're welcome :)

**Pull request merged**
