### PR TITLE
Add DateTime stub

### PR DESCRIPTION
**Pull request by othercorey**
closes https://github.com/vimeo/psalm/issues/3358

This is a copy of DateTimeImmutable with the psalm-mutation-free tags removed where appropriate.

Moved the attributes the top of the file for better organization

### CODE REVIEW

**Comment by othercorey** [comment]
I'm not sure I follow what this failing method call test is trying to check:

```php
'datetimeformatNotFalse' => [
    'code' => '<?php
        $format = random_bytes(10);
        $dt = new DateTime;
        $formatted = $dt->format($format);
        if (false !== $formatted) {}
        function takesString(string $s) : void {}
        takesString($formatted);',
    'assertions' => [],
    'ignored_issues' => [],
    'php_version' =>  '7.4',
],
```

**Comment by weirdan** [comment]
> I'm not sure I follow what this failing method call test is trying to check

Apparently, it's a test ensuring there's `@psalm-ignore-falsable-return` on that method.

`if (false !== $formatted) {}` ensures that checks against `false` are allowed and not considered redundant.

`takesString($formatted);` validates that checks for `false` are not required.

**Comment by othercorey** [comment]
Ok, that's what I thought, but since DateTime::format() was just in the callmaps before, wasn't sure if it was specific to that method since all callmap falsable returns should be ignored. 

Maybe we can just use a different method?

**Comment by othercorey** [comment]
> Maybe we can just use a different method?

I changed it to use another method that returns false in the callmap. I had to use one that isn't defined in stubs.

These tests aren't labeled very well, but I think it was meant to test the ignore return false of ANY callmap method (not just a function) and isn't specific to Date Time.

**Comment by othercorey** [comment]
@weirdan I now don't understand this failure:

```php
        $this->expectExceptionMessage('LessSpecificImplementedReturnType - somefile.php:5:');

        $this->addFile(
            'somefile.php',
            '<?php

                /**
                 * @method int test()
                 * @method \DateTime modify($modify)
                 */
                class WTF extends \DateTime { }',
        );
```

Why does `static` behave differently from a stub than the callmap? The return type is the same.

**Pull request closed without merging**
