### PR TITLE
Optionally allow trait static calls and property access

### PR DESCRIPTION
**Pull request by danog**
This PR optionally allows static method calls and property access on traits.

### CODE REVIEW

**Comment by danog** [comment]
Hmmm, this introduces a weird issue with typing during property access:
```
<?php
trait a
{
    public static int $a = 0;
}

echo(a::$a);
```

Here, NodeDataProvider::getType(a::$a) returns null, causing a MixedArgument error, but even just adding a `$a = a::$a` seems to correctly populate type information, removing the error:
```
<?php
trait a
{
    public static int $a = 0;
}

$a = a::$a;
echo(a::$a);
```

**Comment by muglug** [comment]
What's the value of allowing this?

**Comment by danog** [comment]
Hi!)
Personally, I don't see any problem with adding this: static trait methods and properties traits behave just as they would in an abstract or normal class, no weird quirks at all.

If traits are used to re-use shared code, I don't see why shouldn't I use static methods when grouping together related logic in a trait.

**Comment by muglug** [comment]
But direct access is just not what traits were designed for, and I don't think Psalm should encourage this (even behind a flag)

**Pull request closed without merging**
