### PR TITLE
do not corrupt internal state when a baseline is present

### LINKED ISSUE #2709: psalm master reports errors which are baselined
Even though we have base-lined `MissingPropertyType` but otherwise treat it as errors, psalm `master` randomly reports some instances as `ERROR` but then still exits with zero exit code and the "No issues found" tagline.

I have tracked this down to 8202af957d044c4ff23842878b2a718f45d3c2c9 where a reference in `foreach()` is reused later on which causes corruption of internal state.

I have a fix too, but I want to provide a failing test too.

### PR DESCRIPTION
**Pull request by pilif**
this fixes #2709

### CODE REVIEW

**Comment by pilif** [comment]
I'm a bit unhappy with the "unit"-test because that's basically an integration test.

However, I don't see another solution as `IsssueBuffer` is all `static` methods and `IssueBuffer::finish()` is huge and accesses a huge swath of dependencies.

(also, this is currently failing the self-test - I'll fix that in a followup)

**Comment by pilif** [comment]
I have force-pushed to fix the issues I was causing. However, self-analyze still reports an issue that's completely unrelated to this PR and also doesn't seem to happen on my local machine 🤷‍♀

**Comment by pilif** [comment]
never mind - I f'ed up a mock. Now there's much more green.

**Comment by pilif** [comment]
the issues on Travis CI / PHP 7.4 are caused by an outdated version of phpunit being used where `$this->createMock()` throws a deprecated warning. 

As I'm unconvinced of the value of this test anyways, I'm not going to dump the dependency version requirement without first having your input.

**Comment by muglug** [comment]
Thanks! So I should wait to merge?

**Comment by pilif** [comment]
> Thanks! So I should wait to merge?

that's up to you to decide.

I can't make the test any better without seriously reworking things but for that I don't feel familiar enough with the project.

If you accept the test as-is, the phpunit dependency would need to be bumpted to `7.5.16` for 7.5. If that's ok, I'll make the change to composer.json

If you think the test is too integration-testy, then I can also remove it.

**Comment by muglug** [comment]
Oh please bump the dep!

**Comment by muglug** [comment]
Actually I'll do it myself

**Pull request merged**
