### PR TITLE
Add support for Iterator<X> type

### PR DESCRIPTION
**Pull request by enumag**
Also added `IteratorAggregate` since `Traversable` is supported but I don't really care about that. I'll revert that if you want.

Should I add a test somewhere?

### CODE REVIEW

**Comment by muglug** [comment]
Would you mind moving the failing test into the valid test set? Because your changes mean it _should_ pass now!

**Comment by enumag** [comment]
Sure I'll look into the failing tests when I get home and try to fix them.

**Comment by weirdan** [comment]
Keep in mind that it'll change the types inferred for codebases that had incomplete params for `Iterator` and some errors suppressed: https://psalm.dev/r/aeb390621b. Previously `Iterator<X>` was interpreted as iterator with keys of type `X` and now it'll become iterator with **values** of type `X`.

**Comment by muglug** [comment]
Yeah, happy for that to happen (for these three fairly obvious cases)

**Comment by enumag** [comment]
Ok, the tests are fixed now. Please review.

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
