### PR TITLE
Add failing test case for parsing a complex type alias

### PR DESCRIPTION
**Pull request by spawnia**
https://github.com/vimeo/psalm/issues/6928

### CODE REVIEW

**Comment by orklah** [comment]
The error is caused by a preg_replace 
https://github.com/vimeo/psalm/commit/a0866da88e605adaa648e9f1ad37f4990650f55c that was added a few years back to skip extra datas at the end of a line. when there is an `array<...>`, this preg_replace matches then `>` and strip what's after, which in case of a `callable(array<string>): void` is pretty bad.

So this is the regex that needs to change. I'd advise dropping the whole preg_replace and see what fails. We'll then see what was the exact use case that needed this

**Comment by spawnia** [comment]
There should be facilities to handle trailing data after a type definition in PHPDocs, for instance when dealing with `@return`. Perhaps there is a common core that can be extracted and reused?

**Comment by orklah** [comment]
I'm aware of `CommentAnalyzer::sanitizeDocblockType`, not sure if it will work though...

**Comment by spawnia** [comment]
Looks like your idea worked though, it looks like the removal of the offending `preg_replace` did indeed cause a regression in the following test case:

```php
<?php
/**
 * @psalm-type MiddlewareArray = array<
 *     class-string<\Exception>,
 *     array<int, string>
 * >
 *
 * @psalm-type RuleArray = array{
 *     rule: string,
 *     controller?: class-string<\Exception>,
 *     redirect?: string,
 *     code?: int,
 *     type?: string,
 *     middleware?: MiddlewareArray
 * }
 *
 * Foo Bar
 */
class A {}
```

If you have further ideas on how to fix this, feel free to work on my branch and edit it directly.

**Comment by orklah** [comment]
So this is what the regex was needed for. I'd suggest you check what output is coming in the variable that was changed and find some other way to strip the extra datas. Maybe the function I gave you above?

**Comment by spawnia** [comment]
I don't plan to do any more work on this pull request. Feel free to use the test case as the basis for an actual fix.

**Pull request closed without merging**
