### PR TITLE
feature: ensure universal object crate class exists

### PR DESCRIPTION
**Pull request by mr-feek**
Ayo -- was playing around with implementing the universal object crates in a project of mine. I typod the classname in the config and took me way too long to realize. This should help out

### CODE REVIEW

**Comment by mr-feek** [comment]
I'll iterate on this to get CI green

**Comment by mr-feek** [comment]
any advice on how to test the universal object crate feature  now @muglug ? This test is now failing  as it should, considering that class does not exist

**Comment by muglug** [comment]
Uhh... use a known class? PHP core has plenty of them...

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
