### PR TITLE
Cleanup outdated comment

### PR DESCRIPTION
**Pull request by andrew-demb**
Follow-up for https://github.com/vimeo/psalm/pull/8694

### CODE REVIEW

**Comment by weirdan** [comment]
@andrew-demb I think CircleCI failure can be fixed by you following the steps in `If you're following the fork instead of the upstream repo` of https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization-

**Comment by andrew-demb** [comment]
> @andrew-demb I think CircleCI failure can be fixed by you following the steps in `If you're following the fork instead of the upstream repo` section of https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization-

Probably it was a case described in "If the branch and the pull request happen to be created simultaneously" chapter

**Comment by weirdan** [comment]
Or that.

**Comment by weirdan** [comment]
Thanks!

**Pull request merged**
