### PR TITLE
Add support for absolute plugin paths.

### PR DESCRIPTION
**Pull request by jwage**
Add support for absolute plugin paths:

```xml
<?xml version="1.0"?>
<psalm>
    <projectFiles>
        <directory name="src" />
    </projectFiles>
    <plugins>
        <plugin filename="/absolute/path/to/StringChecker.php" />
    </plugins>
</psalm>
```

### CODE REVIEW

**Comment by muglug** [comment]
Looks good!

> Checking for an absolute path can get messy to make it work between linux & windows

How so?

**Comment by jwage** [comment]
To make it work consistently in windows you have to support things like `file://c:/path/to/something` and `zlib://c:/path/to/something`. In linux we can just check `if ($path[0] === '/')`. If you are ok with adding something like a `isAbsoluteMethod(string $path)` method somewhere I can do that. Let me know.

**Comment by muglug** [comment]
> If you are ok with adding something like a isAbsoluteMethod(string $path) method somewhere I can do that.

I am enormously OK with that :)

**Comment by muglug** [comment]
It could go in `command_functions.php`, which is available on every req.

**Comment by jwage** [comment]
Ok, I will add it. Do you have any thoughts on how and what to assert here? https://github.com/vimeo/psalm/pull/1602/files#diff-afdc28abe8d80c678910cc44767a2759R799

I noticed some other tests don't have assertions so maybe we don't need it?

**Comment by muglug** [comment]
Yeah I'm not worried about assertions, as long as there's a test that captures the opposite, failing case (here a plugin path that doesn't exist)

**Comment by jwage** [comment]
To make `src/command_functions.php` available to the test suite I had to make a few changes to phpunit bootstrap.

**Comment by jwage** [comment]
Also, this approach may technically be considered a BC break. If someone accidentally had an absolute path before this, I think it would still work as a relative path since it'd be concatenated with the base dir and would have double slashes but it would still work.

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
