### PR TITLE
improve support for modulo operator

### PR DESCRIPTION
**Pull request by SignpostMarv**
~can't quite figure out how to indicate that `101 % 0` is `DivisionByZeroError`~ figured it out in 5ca2518b

### CODE REVIEW

**Comment by SignpostMarv** [comment]
Should `(literalfloat|literalint)  % (literalfloat|literalint)` be resolved as well as literal ints ?

**Comment by muglug** [comment]
Thanks – I appreciate this, but I can't think there's any real-life code that computes the modulus of two known numbers.

**Comment by SignpostMarv** [comment]
> real-life code that computes the modulus of two known numbers.

That was mostly to fix the particular cases in #2562, however, hold that thought....

**Comment by SignpostMarv** [comment]
one could return a union if only one side were known. prepping a diff.

**Comment by SignpostMarv** [comment]
> real-life code that computes the modulus of two known numbers.

* with `random_int()` it can be known
* with `range()` it can be known
* with `foreach ($arr as $index => $value){ echo $index % 2 ? 'odd' : 'even'; }` where `$arr = <list<T>|array<int, T>>` and the size of `$arr` is known, the possible values of `$index` will be known.

**Comment by muglug** [comment]
I think the only useful situation is something like `$i % 3`, where you can say for certain that the result must lie in the range `(1-$i)` to `($i - 1)`. You could transform that into a union of literal numbers for suitably low values of `$i` like 5 or so, but I still think this is a not particularly useful analysis.

**Comment by SignpostMarv** [comment]
> You could transform that into a union of literal numbers for suitably low values

It looks like BinaryOpAnalyzer already handles unions/arrays & boils them back down to literal comparsions.

**Pull request closed without merging**
