### PR TITLE
handle return flag for a try/catch/finally

### PR DESCRIPTION
**Pull request by orklah**
This PR aims to resolve https://github.com/vimeo/psalm/issues/4500

However, it seems pretty crude. I probably did something wrong (or maybe even very wrong!) and I'm about to see that in CI, but it seems to resolve my issue so I take a shot!

### CODE REVIEW

**Comment by muglug** [comment]
Mind adding a test?

**Comment by muglug** [comment]
Mind adding tests that fail on current Psalm?

**Comment by muglug** [comment]
You should add a test in the `tests/FileManipulations` folder, I think

**Comment by orklah** [comment]
> Mind adding tests that fail on current Psalm?

https://psalm.dev/r/baa68b1aa0 didn't do the trick? Anyway, I added my original case in FileManipulations

**Comment by orklah** [comment]
oh, nvm, the error was indeed already reported correctly before. Should I keep the redundant tests I added then?

**Comment by muglug** [comment]
Nah, get rid of those I think

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
