### PR TITLE
Convert finfo functions to use object instead of a resource

### PR DESCRIPTION
**Pull request by tomasnorre**
Resolves: #6402

I'm honestly in doubt how the `finfo` should be written. I don't know if it should be namespaced like the `FTP/Connection` or just `finfo`.

I don't get an indication in the  https://github.com/php/php-src/pull/5987/files/31164d2acd0de1375b24f30175b1c3c67cd56d07

But I'm also not used to read the Source itself, and my PHPStorm I cannot switch to PHP 8.1 to have the auto-complition (jump to source) help me.

Pointers would be a big help. At best a reference to where I see it, then I'll learn from it and not just do that change without knowing why.

### CODE REVIEW

**Comment by tomasnorre** [comment]
Could you please add the #hacktoberfest badge to the project, and hopefully later the #hacktoberfest-accepted to this one, currently it says you're not participating

**Comment by orklah** [comment]
No need for namespacing as finfo exist in global namespace (see https://3v4l.org/h2NYD#v8.1rc2)

PR seems great :) Thanks and congrats for your first PR!

>Could you please add the #hacktoberfest badge to the project

I think it should be done soon. Meanwhile, I added the label to this specific PR, does it works?

**Comment by tomasnorre** [comment]
> I think it should be done soon. Meanwhile, I added the label to this specific PR, does it works?

Not yet, but might be cached. So will check later. Will take 14 days to be finally accepted anyway. So no stress.

**Comment by tomasnorre** [comment]
> No need for namespacing as finfo exist in global namespace (see https://3v4l.org/h2NYD#v8.1rc2)

Didn't think about checking it like that.

**Comment by orklah** [comment]
Thanks!

**Comment by tomasnorre** [comment]
Np. Just happy to help and learn. Thanks for enabling and supporting me to help.

**Pull request merged**
