### PR TITLE
igbinary_serialize code was missing in file

### PR DESCRIPTION
**Pull request by kkmuffme**
For some reason igbinary code was missing in a single file. Added it now.

Fixes https://github.com/vimeo/psalm/issues/8006

### CODE REVIEW

**Comment by kkmuffme** [comment]
The line length limit of 120 is excessively low and just a waste of time. Added a bug 3 times in the perfectly valid code, due to this. Code readability is worse too.
150/180 would be much better.

**Comment by AndrolGenhald** [comment]
Yeah, I tend to use 150 for my own stuff these days. At least it's not the historic limit of 80...

Maybe start a discussion about changing it to get everyone's input?

**Comment by kkmuffme** [comment]
Could someone merge this?

**Comment by orklah** [comment]
Thanks

**Pull request merged**
