### PR TITLE
AssignOp\Concat == BinaryOp\Concat

### PR DESCRIPTION
**Pull request by testanull**
AssignOp\Concat works in the same way as  BinaryOp\Concat
I just change the AssignOp\Concat -> BinaryOp\Concat for correctly working!

### CODE REVIEW

**Comment by muglug** [comment]
I'm not sure this works properly - at least one test is failing

**Comment by weirdan** [comment]
Wow, that's a lot of changes!

**Comment by muglug** [comment]
Yeah, you ran phpcs-fixer I think? Mind undoing that?

**Comment by testanull** [comment]
Sorry about that, 
Btw, how to fix the coding standard problem?
I tested the new AssignmentOp\Concat, it works correctly.
For examples, with these code:
```
<?php
$cmd = $_GET['cmd'];
$cmd .= " hello";
system($cmd);
```

``$cmd .= " hello";``
is the same as
``$cmd = $cmd . " hello";``
But old AssignmentOp\Concat can not detect this

**Pull request closed without merging**
